-- TORVIAN Transfer — Blog Yazıları
-- Supabase SQL Editor'e yapıştır ve çalıştır.
-- Mevcut hiçbir veriyi silmez/değiştirmez.

INSERT INTO blog_posts (slug, title_tr, title_en, title_de, title_pl, title_ru, content_tr, content_en, content_de, content_pl, content_ru, image_url, is_published, published_at) VALUES

(
  'antalya-havalimani-belek-transfer',
  'Antalya Havalimanı''ndan Belek''e Transfer: Fiyat, Süre ve İpuçları 2026',
  'Antalya Airport to Belek Transfer: Price, Duration & Tips 2026',
  'Transfer vom Flughafen Antalya nach Belek: Preis, Dauer & Tipps 2026',
  'Transfer z lotniska Antalya do Belek: Ceny, Czas i Porady 2026',
  'Трансфер из аэропорта Анталии в Белек: цены, время и советы 2026',

  -- content_tr
  E'<h2>Antalya Havalimanı''ndan Belek''e Nasıl Gidilir?</h2>\n<p>Antalya Havalimanı ile Belek arasındaki mesafe yaklaşık 33 km olup normal trafik koşullarında bu yol 25-35 dakika sürmektedir. Dünyaca ünlü golf sahaları ve lüks tatil köyleriyle öne çıkan Belek, her yıl milyonlarca turisti ağırlamaktadır.</p>\n<h2>Transfer Seçenekleri</h2>\n<h3>1. Özel VIP Transfer (Önerilen)</h3>\n<p>Antalya Havalimanı''ndan Belek''e en konforlu ve pratik ulaşım yöntemi özel transferdir. TORVIAN Transfer ile rezervasyon yaptığınızda:</p>\n<ul>\n<li>Sabit fiyat garantisi — gizli ücret yok</li>\n<li>Uçuş gecikme takibi — bekleme ücreti yok</li>\n<li>Havalimanında karşılama — isim tabelası ile</li>\n<li>Kapıdan kapıya hizmet — direkt otelinize</li>\n<li>7/24 WhatsApp destek</li>\n</ul>\n<h3>2. Taksi</h3>\n<p>Havalimanı taksileri genellikle 800-1200 TL arasında ücret talep eder, ancak sabit tarife olmadığından fiyat değişkenlik gösterebilir.</p>\n<h3>3. Otobüs</h3>\n<p>Havalimanından Belek''e direkt otobüs seferi bulunmamaktadır. Antalya şehir merkezi üzerinden aktarmalı ulaşım 1,5-2 saat sürebilir.</p>\n<h2>Belek Transfer Fiyatları 2026</h2>\n<p>TORVIAN Transfer ile Antalya Havalimanı''ndan Belek''e transfer fiyatları araç tipine göre değişmekte olup online rezervasyon yaparak en güncel fiyatları görebilirsiniz. Tüm fiyatlar kişi başı değil, araç başı sabit fiyattır.</p>\n<h2>Sık Sorulan Sorular</h2>\n<h3>Belek''e transfer kaç dakika sürer?</h3>\n<p>Havalimanından Belek''e ortalama 25-35 dakika sürmektedir.</p>\n<h3>Gece transferi mümkün mü?</h3>\n<p>Evet, TORVIAN Transfer 7/24 hizmet vermektedir. Gece geç saatlerde veya sabahın erken saatlerinde gelen uçuşlar için de aynı konforlu hizmet sunulmaktadır.</p>\n<h3>Kaç kişiye kadar araç var?</h3>\n<p>Standart araçtan minibüse kadar farklı kapasitelerde araç seçenekleri mevcuttur. Grup transferleri için de rezervasyon yapılabilir.</p>',

  -- content_en
  E'<h2>How to Get from Antalya Airport to Belek?</h2>\n<p>Belek is located approximately 33 km from Antalya Airport. Under normal traffic conditions, the journey takes around 25-35 minutes. Famous for its world-class golf courses and luxury resorts, Belek welcomes millions of tourists every year.</p>\n<h2>Transfer Options</h2>\n<h3>1. Private VIP Transfer (Recommended)</h3>\n<p>A private transfer is the most comfortable and practical way to reach Belek from Antalya Airport. When you book with TORVIAN Transfer, you get:</p>\n<ul>\n<li>Fixed price guarantee — no hidden fees</li>\n<li>Flight delay tracking — no waiting surcharge</li>\n<li>Meet & greet at the airport — with name board</li>\n<li>Door-to-door service — directly to your hotel</li>\n<li>24/7 WhatsApp support</li>\n</ul>\n<h3>2. Taxi</h3>\n<p>Airport taxis typically charge between 800-1200 TL, but fares may vary as there is no fixed tariff.</p>\n<h3>3. Bus</h3>\n<p>There is no direct bus from the airport to Belek. Travelling via Antalya city centre with a transfer can take 1.5-2 hours.</p>\n<h2>Belek Transfer Prices 2026</h2>\n<p>TORVIAN Transfer prices from Antalya Airport to Belek vary by vehicle type. All prices are fixed per vehicle, not per person. Book online to see the latest prices.</p>\n<h2>Frequently Asked Questions</h2>\n<h3>How long does the transfer to Belek take?</h3>\n<p>The journey from the airport to Belek takes an average of 25-35 minutes.</p>\n<h3>Is a night transfer possible?</h3>\n<p>Yes, TORVIAN Transfer operates 24/7. The same comfortable service is provided for late-night or early-morning arrivals.</p>\n<h3>How many passengers can be accommodated?</h3>\n<p>Vehicle options range from standard cars to minibuses. Group bookings are also available.</p>',

  -- content_de
  E'<h2>Wie komme ich vom Flughafen Antalya nach Belek?</h2>\n<p>Belek liegt etwa 33 km vom Flughafen Antalya entfernt. Unter normalen Verkehrsbedingungen dauert die Fahrt etwa 25-35 Minuten. Belek ist bekannt für seine weltklasse Golfplätze und Luxusresorts.</p>\n<h2>Transfermöglichkeiten</h2>\n<h3>1. Privater VIP-Transfer (Empfohlen)</h3>\n<p>Ein Privattransfer ist die komfortabelste und praktischste Möglichkeit, von Antalya nach Belek zu gelangen. Bei TORVIAN Transfer erhalten Sie:</p>\n<ul>\n<li>Festpreisgarantie — keine versteckten Kosten</li>\n<li>Flugverspätungsverfolgung — kein Warteaufschlag</li>\n<li>Empfang am Flughafen — mit Namensschild</li>\n<li>Tür-zu-Tür-Service — direkt zu Ihrem Hotel</li>\n<li>24/7 WhatsApp-Support</li>\n</ul>\n<h3>2. Taxi</h3>\n<p>Flughafentaxis berechnen in der Regel 800-1200 TL, aber die Preise können variieren, da es keinen Festtarif gibt.</p>\n<h3>3. Bus</h3>\n<p>Es gibt keinen Direktbus vom Flughafen nach Belek. Die Fahrt über das Stadtzentrum von Antalya mit Umstieg kann 1,5-2 Stunden dauern.</p>\n<h2>Transferpreise Belek 2026</h2>\n<p>Die Preise von TORVIAN Transfer variieren je nach Fahrzeugtyp. Alle Preise sind Festpreise pro Fahrzeug, nicht pro Person. Buchen Sie online, um die aktuellen Preise zu sehen.</p>\n<h2>Häufig gestellte Fragen</h2>\n<h3>Wie lange dauert der Transfer nach Belek?</h3>\n<p>Die Fahrt vom Flughafen nach Belek dauert durchschnittlich 25-35 Minuten.</p>\n<h3>Ist ein Nachttransfer möglich?</h3>\n<p>Ja, TORVIAN Transfer ist 24/7 in Betrieb. Auch für Spätankunft oder Frühmorgenankünfte wird derselbe komfortable Service angeboten.</p>',

  -- content_pl
  E'<h2>Jak dostać się z lotniska Antalya do Belek?</h2>\n<p>Belek leży około 33 km od lotniska Antalya. W normalnych warunkach drogowych podróż trwa około 25-35 minut. Belek słynie z światowej klasy pól golfowych i luksusowych ośrodków wypoczynkowych.</p>\n<h2>Opcje transferu</h2>\n<h3>1. Prywatny transfer VIP (Zalecany)</h3>\n<p>Prywatny transfer to najwygodniejszy i najbardziej praktyczny sposób dotarcia do Belek. Rezerwując z TORVIAN Transfer, otrzymujesz:</p>\n<ul>\n<li>Gwarancja stałej ceny — bez ukrytych opłat</li>\n<li>Śledzenie opóźnień lotów — bez dodatkowych opłat za oczekiwanie</li>\n<li>Powitanie na lotnisku — z tabliczką z Twoim imieniem</li>\n<li>Usługa door-to-door — bezpośrednio do Twojego hotelu</li>\n<li>Wsparcie WhatsApp 24/7</li>\n</ul>\n<h3>2. Taksówka</h3>\n<p>Taksówki lotniskowe zazwyczaj pobierają od 800 do 1200 TL, ale opłaty mogą się różnić, ponieważ nie ma stałego cennika.</p>\n<h3>3. Autobus</h3>\n<p>Nie ma bezpośredniego autobusu z lotniska do Belek. Podróż przez centrum Antalyi z przesiadką może zająć 1,5-2 godziny.</p>\n<h2>Ceny transferu do Belek 2026</h2>\n<p>Ceny TORVIAN Transfer różnią się w zależności od typu pojazdu. Wszystkie ceny są stałe za pojazd, a nie za osobę. Zarezerwuj online, aby zobaczyć aktualne ceny.</p>',

  -- content_ru
  E'<h2>Как добраться из аэропорта Анталии в Белек?</h2>\n<p>Белек находится примерно в 33 км от аэропорта Анталии. В обычных дорожных условиях дорога занимает около 25-35 минут. Белек известен своими гольф-клубами мирового класса и роскошными курортами.</p>\n<h2>Варианты трансфера</h2>\n<h3>1. Частный VIP-трансфер (рекомендуется)</h3>\n<p>Частный трансфер — самый комфортный и практичный способ добраться до Белека. Бронируя у TORVIAN Transfer, вы получаете:</p>\n<ul>\n<li>Гарантия фиксированной цены — никаких скрытых платежей</li>\n<li>Отслеживание задержек рейсов — без доплаты за ожидание</li>\n<li>Встреча в аэропорту — с табличкой с вашим именем</li>\n<li>Услуга от двери до двери — прямо до вашего отеля</li>\n<li>Поддержка WhatsApp 24/7</li>\n</ul>\n<h3>2. Такси</h3>\n<p>Аэропортовые такси обычно берут от 800 до 1200 TL, но тарифы могут варьироваться, так как фиксированного расценки нет.</p>\n<h3>3. Автобус</h3>\n<p>Прямого автобуса из аэропорта в Белек нет. Поездка через центр Анталии с пересадкой может занять 1,5-2 часа.</p>\n<h2>Цены на трансфер в Белек 2026</h2>\n<p>Цены TORVIAN Transfer варьируются в зависимости от типа транспортного средства. Все цены фиксированы за автомобиль, а не за человека. Забронируйте онлайн, чтобы узнать актуальные цены.</p>',

  '/images/regions/belek-golf.jpg',
  true,
  NOW() - INTERVAL '4 days'
),

(
  'antalya-havalimani-alanya-transfer-kac-saat',
  'Antalya Havalimanı''ndan Alanya''ya Kaç Saat Sürer? 2026 Rehberi',
  'How Long is the Transfer from Antalya Airport to Alanya? 2026 Guide',
  'Wie lange dauert der Transfer vom Flughafen Antalya nach Alanya? Ratgeber 2026',
  'Jak długo trwa transfer z lotniska Antalya do Alanyi? Przewodnik 2026',
  'Сколько времени занимает трансфер из аэропорта Анталии в Аланью? Руководство 2026',

  E'<h2>Antalya''dan Alanya''ya Mesafe ve Süre</h2>\n<p>Antalya Havalimanı ile Alanya arasındaki mesafe yaklaşık 132 km''dir. D400 karayolu üzerinden yapılan bu yolculuk, trafik ve hız durumuna göre <strong>1 saat 45 dakika ile 2 saat 15 dakika</strong> arasında sürmektedir.</p>\n<h2>Alanya''ya Nasıl Gidilir?</h2>\n<h3>Özel Transfer</h3>\n<p>En konforlu seçenek. Eşyalarınızla birlikte doğrudan otelinize ulaşırsınız. TORVIAN Transfer ile sabit fiyat, uçuş takibi ve 7/24 destek garantisi alırsınız. Özellikle aile grupları ve fazla bagajlı yolcular için idealdir.</p>\n<h3>Otobüs</h3>\n<p>Antalya otogarından Alanya''ya düzenli otobüs seferleri bulunmaktadır. Ancak havalimanından otogar''a ayrıca ulaşmanız gerekir. Toplam süre 3-4 saati bulabilir.</p>\n<h3>Araç Kiralama</h3>\n<p>Alanya''da kalış süresince gezmeyi planlıyorsanız araç kiralama değerlendirilebilir. Ancak uzun yol yorgunluğu, otopark sorunları ve yakıt maliyeti hesaba katılmalıdır.</p>\n<h2>Alanya Transfer İpuçları</h2>\n<ul>\n<li>Gece uçuşlarında yol boş olduğundan süre 1 saat 30 dakikaya düşebilir</li>\n<li>Yaz sezonunda (Haziran-Ağustos) D400 üzerinde trafik yoğunluğu oluşabilir</li>\n<li>Çocuklu aileler için bebek koltuğu seçeneği ücret sorulmadan eklenebilir</li>\n<li>Alanya merkezine ek olarak Mahmutlar, Okurcalar, Türkler bölgelerine de hizmet verilmektedir</li>\n</ul>\n<h2>Sık Sorulan Sorular</h2>\n<h3>Alanya transfer fiyatı ne kadar?</h3>\n<p>Fiyatlar araç tipine ve yolcu sayısına göre değişir. Güncel fiyatlar için online rezervasyon formunu kullanabilirsiniz.</p>\n<h3>Geç gece transferi mümkün mü?</h3>\n<p>Evet. TORVIAN Transfer gece 00:00-06:00 saatleri dahil hizmet vermektedir, ek ücret uygulanmaz.</p>',

  E'<h2>Antalya to Alanya Distance and Travel Time</h2>\n<p>The distance between Antalya Airport and Alanya is approximately 132 km. Via the D400 highway, the journey takes <strong>1 hour 45 minutes to 2 hours 15 minutes</strong> depending on traffic and speed.</p>\n<h2>How to Get to Alanya?</h2>\n<h3>Private Transfer</h3>\n<p>The most comfortable option. You travel directly to your hotel with all your luggage. With TORVIAN Transfer you get a fixed price, flight tracking and 24/7 support — ideal for families and passengers with heavy luggage.</p>\n<h3>Bus</h3>\n<p>Regular buses run from Antalya bus station to Alanya, but you still need to get from the airport to the bus station. Total travel time can be 3-4 hours.</p>\n<h3>Car Rental</h3>\n<p>An option if you plan to explore Alanya during your stay, but road fatigue, parking issues and fuel costs should be factored in.</p>\n<h2>Alanya Transfer Tips</h2>\n<ul>\n<li>Night flights benefit from quieter roads — journey time can drop to 1 hour 30 minutes</li>\n<li>Summer season (June-August) may see heavier traffic on the D400</li>\n<li>Baby seats are available for families at no extra charge</li>\n<li>Service also covers Mahmutlar, Okurcalar and Türkler areas near Alanya</li>\n</ul>\n<h2>Frequently Asked Questions</h2>\n<h3>How much does an Alanya transfer cost?</h3>\n<p>Prices vary by vehicle type and passenger count. Use the online booking form for current pricing.</p>\n<h3>Is a late-night transfer possible?</h3>\n<p>Yes. TORVIAN Transfer operates around the clock including midnight to 6am, with no extra charge.</p>',

  E'<h2>Entfernung und Reisezeit von Antalya nach Alanya</h2>\n<p>Die Entfernung zwischen dem Flughafen Antalya und Alanya beträgt etwa 132 km. Über die D400-Autobahn dauert die Fahrt je nach Verkehr und Geschwindigkeit <strong>1 Stunde 45 Minuten bis 2 Stunden 15 Minuten</strong>.</p>\n<h2>Wie kommt man nach Alanya?</h2>\n<h3>Privater Transfer</h3>\n<p>Die komfortabelste Option. Sie fahren direkt mit Ihrem gesamten Gepäck zum Hotel. Bei TORVIAN Transfer erhalten Sie einen Festpreis, Flugverfolgung und 24/7-Support — ideal für Familien und Reisende mit viel Gepäck.</p>\n<h3>Bus</h3>\n<p>Vom Busbahnhof Antalya fahren regelmäßige Busse nach Alanya, aber Sie müssen erst vom Flughafen zum Busbahnhof gelangen. Die Gesamtreisezeit kann 3-4 Stunden betragen.</p>\n<h3>Mietwagen</h3>\n<p>Eine Option, wenn Sie vorhaben, Alanya während Ihres Aufenthalts zu erkunden. Beachten Sie jedoch Fahrermüdigkeit, Parkprobleme und Kraftstoffkosten.</p>\n<h2>Tipps für den Alanya-Transfer</h2>\n<ul>\n<li>Nachtflüge profitieren von ruhigeren Straßen — Fahrzeit kann auf 1 Stunde 30 Minuten sinken</li>\n<li>Im Sommer (Juni-August) kann es auf der D400 zu mehr Verkehr kommen</li>\n<li>Babysitze für Familien ohne Aufpreis erhältlich</li>\n</ul>',

  E'<h2>Odległość i czas podróży z Antalyi do Alanyi</h2>\n<p>Odległość między lotniskiem Antalya a Alanyą wynosi około 132 km. Trasa drogą D400 zajmuje <strong>od 1 godziny 45 minut do 2 godzin 15 minut</strong> w zależności od ruchu drogowego.</p>\n<h2>Jak dostać się do Alanyi?</h2>\n<h3>Prywatny transfer</h3>\n<p>Najwygodniejsza opcja. Podróżujesz bezpośrednio do hotelu z całym bagażem. Z TORVIAN Transfer otrzymujesz stałą cenę, śledzenie lotu i wsparcie 24/7 — idealne dla rodzin i pasażerów z dużym bagażem.</p>\n<h3>Autobus</h3>\n<p>Z dworca autobusowego w Antalyi kursują regularne autobusy do Alanyi, ale najpierw trzeba dostać się z lotniska na dworzec. Całkowity czas podróży może wynosić 3-4 godziny.</p>\n<h3>Wynajem samochodu</h3>\n<p>Opcja, jeśli planujesz zwiedzać Alanyę podczas pobytu. Jednak zmęczenie jazdą, problemy z parkowaniem i koszt paliwa powinny być brane pod uwagę.</p>',

  E'<h2>Расстояние и время в пути из Анталии в Аланью</h2>\n<p>Расстояние между аэропортом Анталии и Аланьей составляет около 132 км. По трассе D400 поездка занимает <strong>от 1 часа 45 минут до 2 часов 15 минут</strong> в зависимости от трафика.</p>\n<h2>Как добраться до Аланьи?</h2>\n<h3>Частный трансфер</h3>\n<p>Самый комфортный вариант. Вы едете прямо в отель со всем багажом. С TORVIAN Transfer вы получаете фиксированную цену, отслеживание рейса и поддержку 24/7 — идеально для семей и пассажиров с большим багажом.</p>\n<h3>Автобус</h3>\n<p>С автовокзала Анталии отправляются регулярные автобусы в Аланью, но сначала нужно добраться от аэропорта до автовокзала. Общее время в пути может составить 3-4 часа.</p>\n<h3>Аренда автомобиля</h3>\n<p>Вариант, если вы планируете самостоятельно исследовать Аланью. Однако следует учитывать усталость от вождения, проблемы с парковкой и расходы на топливо.</p>',

  '/images/regions/alanya-castle.jpg',
  true,
  NOW() - INTERVAL '3 days'
),

(
  'antalya-taksi-mi-ozel-transfer-mi',
  'Antalya Havalimanı''nda Taksi mi, Özel Transfer mi? 2026 Karşılaştırması',
  'Antalya Airport: Taxi vs Private Transfer? Which is Better in 2026?',
  'Antalya Flughafen: Taxi oder Privattransfer? Vergleich 2026',
  'Lotnisko Antalya: Taksówka czy prywatny transfer? Porównanie 2026',
  'Аэропорт Анталии: такси или частный трансфер? Сравнение 2026',

  E'<h2>Antalya Havalimanı''nda Ulaşım Seçenekleri</h2>\n<p>Her yıl 40 milyonun üzerinde yolcuya hizmet veren Antalya Havalimanı, Türkiye''nin en yoğun ikinci havalimanıdır. Havalimanından çıktığınızda önünüzde birkaç ulaşım seçeneği bulunur. Peki hangisi sizin için doğru?</p>\n<h2>Fiyat Karşılaştırması</h2>\n<p>Taksilerde sabit tarife bulunmadığından fiyatlar sürücüye göre değişkenlik gösterir. Özellikle yoğun turizm sezonunda fahiş fiyatlarla karşılaşmak mümkündür. Özel transfer hizmetlerinde ise fiyat rezervasyon aşamasında sabitlenerek sözleşmeye bağlanır — sürpriz yoktur.</p>\n<h2>Konfor ve Araç Kalitesi</h2>\n<p>Taksiler genellikle standart binek araçlardır ve bagaj kapasitesi sınırlıdır. Özel transfer hizmetlerinde sedan, SUV ve minibüs gibi farklı araç seçenekleri bulunur. TORVIAN Transfer''de tüm araçlar klimalı, temiz ve bakımlıdır.</p>\n<h2>Güvenilirlik</h2>\n<table>\n<tr><th>Özellik</th><th>Taksi</th><th>Özel Transfer</th></tr>\n<tr><td>Sabit fiyat</td><td>❌</td><td>✅</td></tr>\n<tr><td>Uçuş takibi</td><td>❌</td><td>✅</td></tr>\n<tr><td>Karşılama</td><td>❌</td><td>✅</td></tr>\n<tr><td>Online rezervasyon</td><td>❌</td><td>✅</td></tr>\n<tr><td>7/24 destek</td><td>❌</td><td>✅</td></tr>\n</table>\n<h2>Ne Zaman Hangi Seçenek?</h2>\n<p><strong>Taksiyi tercih edebilirsiniz:</strong> Kısa mesafe, az bagaj ve spontane seyahat için.</p>\n<p><strong>Özel transferi tercih edin:</strong> Aile tatili, büyük grup, fazla bagaj, önceden bilinen geliş saati veya uzun mesafe (Alanya, Side, Kaş) için. Özellikle çocuklu aileler için yer rezervasyonu ve çocuk koltuğu imkânı kritik öneme sahiptir.</p>\n<h2>Sonuç</h2>\n<p>Antalya Havalimanı''ndan konforlu, güvenli ve öngörülebilir bir ulaşım istiyorsanız özel transfer en akıllı seçimdir. TORVIAN Transfer ile online rezervasyonunuzu şimdi yapabilirsiniz.</p>',

  E'<h2>Transport Options at Antalya Airport</h2>\n<p>Serving over 40 million passengers a year, Antalya Airport is Turkey''s second busiest airport. When you exit the terminal, you have several transport options. So which one is right for you?</p>\n<h2>Price Comparison</h2>\n<p>Taxis have no fixed tariff, so prices vary by driver. Overcharging is common during peak tourist season. Private transfer prices are fixed at booking — no surprises.</p>\n<h2>Comfort and Vehicle Quality</h2>\n<p>Taxis are usually standard saloon cars with limited luggage capacity. Private transfers offer sedans, SUVs and minibuses. All TORVIAN Transfer vehicles are air-conditioned, clean and well-maintained.</p>\n<h2>Reliability Comparison</h2>\n<table>\n<tr><th>Feature</th><th>Taxi</th><th>Private Transfer</th></tr>\n<tr><td>Fixed price</td><td>❌</td><td>✅</td></tr>\n<tr><td>Flight tracking</td><td>❌</td><td>✅</td></tr>\n<tr><td>Meet & greet</td><td>❌</td><td>✅</td></tr>\n<tr><td>Online booking</td><td>❌</td><td>✅</td></tr>\n<tr><td>24/7 support</td><td>❌</td><td>✅</td></tr>\n</table>\n<h2>When to Choose Which?</h2>\n<p><strong>Choose a taxi:</strong> Short distances, minimal luggage, spontaneous travel.</p>\n<p><strong>Choose private transfer:</strong> Family holidays, large groups, heavy luggage, known arrival time, or long distances (Alanya, Side, Kaş). Child seats and pre-booked capacity are especially important for families.</p>\n<h2>Conclusion</h2>\n<p>If you want comfortable, safe and predictable transport from Antalya Airport, a private transfer is the smartest choice. Book online with TORVIAN Transfer now.</p>',

  E'<h2>Transportmöglichkeiten am Flughafen Antalya</h2>\n<p>Mit über 40 Millionen Passagieren pro Jahr ist der Flughafen Antalya der zweitgrößte Flughafen der Türkei. Wenn Sie das Terminal verlassen, haben Sie mehrere Transportmöglichkeiten. Welche ist die richtige für Sie?</p>\n<h2>Preisvergleich</h2>\n<p>Taxis haben keinen Festtarif, die Preise variieren je nach Fahrer. Überhöhte Preise sind in der Hochsaison üblich. Privattransferpreise werden bei der Buchung festgelegt — keine Überraschungen.</p>\n<h2>Zuverlässigkeitsvergleich</h2>\n<table>\n<tr><th>Merkmal</th><th>Taxi</th><th>Privattransfer</th></tr>\n<tr><td>Festpreis</td><td>❌</td><td>✅</td></tr>\n<tr><td>Flugverfolgung</td><td>❌</td><td>✅</td></tr>\n<tr><td>Empfang</td><td>❌</td><td>✅</td></tr>\n<tr><td>Online-Buchung</td><td>❌</td><td>✅</td></tr>\n<tr><td>24/7-Support</td><td>❌</td><td>✅</td></tr>\n</table>\n<h2>Fazit</h2>\n<p>Wenn Sie einen komfortablen, sicheren und planbaren Transfer vom Flughafen Antalya wünschen, ist der Privattransfer die klügste Wahl. Buchen Sie jetzt online bei TORVIAN Transfer.</p>',

  E'<h2>Opcje transportu na lotnisku Antalya</h2>\n<p>Obsługując ponad 40 milionów pasażerów rocznie, lotnisko Antalya jest drugim co do wielkości lotniskiem w Turcji. Po wyjściu z terminalu masz kilka opcji transportu. Która jest dla Ciebie odpowiednia?</p>\n<h2>Porównanie cen</h2>\n<p>Taksówki nie mają stałych taryf, więc ceny różnią się w zależności od kierowcy. Zawyżanie cen jest powszechne w szczycie sezonu turystycznego. Ceny prywatnych transferów są ustalone przy rezerwacji — bez niespodzianek.</p>\n<h2>Porównanie niezawodności</h2>\n<table>\n<tr><th>Cecha</th><th>Taksówka</th><th>Prywatny transfer</th></tr>\n<tr><td>Stała cena</td><td>❌</td><td>✅</td></tr>\n<tr><td>Śledzenie lotu</td><td>❌</td><td>✅</td></tr>\n<tr><td>Powitanie</td><td>❌</td><td>✅</td></tr>\n<tr><td>Rezerwacja online</td><td>❌</td><td>✅</td></tr>\n<tr><td>Wsparcie 24/7</td><td>❌</td><td>✅</td></tr>\n</table>\n<h2>Wniosek</h2>\n<p>Jeśli chcesz wygodnego, bezpiecznego i przewidywalnego transportu z lotniska Antalya, prywatny transfer jest najmądrzejszym wyborem. Zarezerwuj online z TORVIAN Transfer już teraz.</p>',

  E'<h2>Варианты транспорта в аэропорту Анталии</h2>\n<p>Обслуживая более 40 миллионов пассажиров в год, аэропорт Анталии является вторым по загруженности аэропортом Турции. Выходя из терминала, у вас есть несколько вариантов транспорта. Какой из них подходит именно вам?</p>\n<h2>Сравнение цен</h2>\n<p>У такси нет фиксированных тарифов, поэтому цены варьируются в зависимости от водителя. Завышение цен распространено в разгар туристического сезона. Цены на частные трансферы фиксируются при бронировании — никаких сюрпризов.</p>\n<h2>Сравнение надёжности</h2>\n<table>\n<tr><th>Характеристика</th><th>Такси</th><th>Частный трансфер</th></tr>\n<tr><td>Фиксированная цена</td><td>❌</td><td>✅</td></tr>\n<tr><td>Отслеживание рейса</td><td>❌</td><td>✅</td></tr>\n<tr><td>Встреча</td><td>❌</td><td>✅</td></tr>\n<tr><td>Онлайн-бронирование</td><td>❌</td><td>✅</td></tr>\n<tr><td>Поддержка 24/7</td><td>❌</td><td>✅</td></tr>\n</table>\n<h2>Вывод</h2>\n<p>Если вы хотите комфортного, безопасного и предсказуемого трансфера из аэропорта Анталии — частный трансфер является самым разумным выбором. Забронируйте онлайн с TORVIAN Transfer.</p>',

  '/images/5312.jpg',
  true,
  NOW() - INTERVAL '2 days'
),

(
  'antalya-havalimani-side-transfer',
  'Antalya Havalimanı''ndan Side''ye Transfer Rehberi 2026',
  'Antalya Airport to Side Transfer: Complete Guide 2026',
  'Transfer vom Flughafen Antalya nach Side: Vollständiger Ratgeber 2026',
  'Transfer z lotniska Antalya do Side: Kompletny przewodnik 2026',
  'Трансфер из аэропорта Анталии в Сиде: полное руководство 2026',

  E'<h2>Antalya''dan Side''ye Mesafe ve Süre</h2>\n<p>Antalya Havalimanı''ndan Side''ye olan mesafe yaklaşık 65 km''dir. D400 karayolunu kullanan bir özel araç bu mesafeyi normal koşullarda <strong>50-60 dakika</strong>da kat eder.</p>\n<h2>Side Hakkında</h2>\n<p>Side, antik Rum tapınakları, Akdeniz''e bakan gün batımı manzarası ve her bütçeye uygun oteliyle Türkiye''nin en çok tercih edilen tatil destinasyonlarından biridir. Her yıl yüz binlerce Avrupalı turist tarafından ziyaret edilmektedir.</p>\n<h2>Side Transfer Seçenekleri</h2>\n<h3>Özel VIP Transfer</h3>\n<p>TORVIAN Transfer ile Side''ye özel transfer rezervasyonu yaparak sabit fiyat, uçuş takibi ve kapıdan kapıya hizmetin keyfini çıkarabilirsiniz. Belek üzerinden geçiş güzergâhı sayesinde golf tesislerine de uğrama imkânı bulunmaktadır.</p>\n<h3>Tur Otobüsü Transferi</h3>\n<p>Birçok tur operatörü havalimanı-Side arası servis sunmaktadır. Ancak diğer yolcuları beklemek, ara duraklar ve paylaşımlı araçlar konfor seviyesini düşürebilir.</p>\n<h2>Side Bölgesinde Hizmet Verilen Oteller</h2>\n<p>Side merkezi, Kumköy, Çolakli, Evrenseki, Kadriye ve Boğazkent bölgelerine transferlerimiz mevcuttur.</p>\n<h2>İpuçları</h2>\n<ul>\n<li>Side''nin antik kenti araç girişine kapalıdır. Otel bölgesine bırakılırsınız.</li>\n<li>Yoğun sezonda (Temmuz-Ağustos) hafta sonları trafik yoğunlaşabilir.</li>\n<li>Dönüş transferi için de reservasyon yapmanız tavsiye edilir.</li>\n</ul>',

  E'<h2>Antalya to Side Distance and Duration</h2>\n<p>The distance from Antalya Airport to Side is approximately 65 km. A private vehicle via the D400 highway covers this distance in <strong>50-60 minutes</strong> under normal conditions.</p>\n<h2>About Side</h2>\n<p>Side is one of Turkey''s most popular holiday destinations, featuring ancient Greek temples, stunning Mediterranean sunsets, and hotels to suit every budget. It attracts hundreds of thousands of European tourists each year.</p>\n<h2>Side Transfer Options</h2>\n<h3>Private VIP Transfer</h3>\n<p>Book a private transfer to Side with TORVIAN Transfer and enjoy a fixed price, flight tracking and door-to-door service. The route also passes through Belek, offering the option to stop at golf facilities.</p>\n<h3>Shared Shuttle</h3>\n<p>Many tour operators offer airport-to-Side shuttles, but waiting for other passengers, intermediate stops and shared vehicles reduce comfort significantly.</p>\n<h2>Areas Served in the Side Region</h2>\n<p>We serve Side centre, Kumköy, Çolakli, Evrenseki, Kadriye and Boğazkent.</p>\n<h2>Tips</h2>\n<ul>\n<li>Vehicles cannot enter Side''s ancient city centre — you will be dropped at the hotel zone.</li>\n<li>Weekend traffic can increase during peak season (July-August).</li>\n<li>We recommend booking a return transfer in advance.</li>\n</ul>',

  E'<h2>Entfernung und Reisezeit von Antalya nach Side</h2>\n<p>Die Entfernung vom Flughafen Antalya nach Side beträgt etwa 65 km. Ein Privatfahrzeug über die D400-Autobahn bewältigt diese Strecke unter normalen Bedingungen in <strong>50-60 Minuten</strong>.</p>\n<h2>Über Side</h2>\n<p>Side ist eines der beliebtesten Urlaubsziele der Türkei mit antiken griechischen Tempeln, atemberaubenden Mittelmeer-Sonnenuntergängen und Hotels für jeden Geldbeutel. Es zieht jährlich Hunderttausende europäischer Touristen an.</p>\n<h2>Side-Transferoptionen</h2>\n<h3>Privater VIP-Transfer</h3>\n<p>Buchen Sie mit TORVIAN Transfer einen Privattransfer nach Side und genießen Sie einen Festpreis, Flugverfolgung und Tür-zu-Tür-Service.</p>\n<h2>Bediente Gebiete in der Side-Region</h2>\n<p>Wir bedienen Side Zentrum, Kumköy, Çolakli, Evrenseki, Kadriye und Boğazkent.</p>',

  E'<h2>Odległość i czas podróży z Antalyi do Side</h2>\n<p>Odległość z lotniska Antalya do Side wynosi około 65 km. Pojazd prywatny trasą D400 pokonuje tę odległość w <strong>50-60 minut</strong> w normalnych warunkach.</p>\n<h2>O Side</h2>\n<p>Side to jedno z najpopularniejszych miejsc wakacyjnych w Turcji, ze starożytnymi świątyniami greckimi, zapierającymi dech zachodami słońca nad Morzem Śródziemnym i hotelami dla każdego budżetu.</p>\n<h2>Obsługiwane obszary w regionie Side</h2>\n<p>Obsługujemy centrum Side, Kumköy, Çolakli, Evrenseki, Kadriye i Boğazkent.</p>',

  E'<h2>Расстояние и время в пути из Анталии в Сиде</h2>\n<p>Расстояние от аэропорта Анталии до Сиде составляет около 65 км. Частный автомобиль по трассе D400 преодолевает это расстояние за <strong>50-60 минут</strong> в обычных условиях.</p>\n<h2>О Сиде</h2>\n<p>Сиде — одно из самых популярных туристических направлений Турции с древнегреческими храмами, потрясающими закатами над Средиземным морем и отелями на любой бюджет.</p>\n<h2>Обслуживаемые районы в регионе Сиде</h2>\n<p>Мы обслуживаем центр Сиде, Кумкёй, Чолаклы, Эврензеки, Кадрие и Богазкент.</p>',

  '/images/regions/side-ancient.jpg',
  true,
  NOW() - INTERVAL '1 day'
),

(
  'antalya-havalimani-kemer-transfer',
  'Antalya Havalimanı''ndan Kemer''e Ulaşım: En İyi Seçenekler 2026',
  'Antalya Airport to Kemer: Best Transfer Options 2026',
  'Vom Flughafen Antalya nach Kemer: Die besten Transferoptionen 2026',
  'Z lotniska Antalya do Kemer: Najlepsze opcje transferu 2026',
  'Из аэропорта Анталии в Кемер: лучшие варианты трансфера 2026',

  E'<h2>Antalya Havalimanı ile Kemer Arasındaki Mesafe</h2>\n<p>Antalya Havalimanı''ndan Kemer''e olan mesafe yaklaşık 43 km olmakla birlikte rota dağlık araziden geçtiğinden seyahat süresi <strong>40-55 dakika</strong> arasında değişir. Toros Dağları''nın eteklerinde, Akdeniz kıyısında yer alan Kemer; Phaselis antik kenti, Olympos ve doğa parkurlarıyla eşsiz bir tatil deneyimi sunar.</p>\n<h2>Transfer Seçenekleri</h2>\n<h3>Özel Transfer (En İyi Seçenek)</h3>\n<p>Havalimanından doğrudan otelinize kapıdan kapıya hizmet. Yolda dağ manzarasının keyfini çıkarırken ulaşım sorunu yaşamazsınız. TORVIAN Transfer ile:</p>\n<ul>\n<li>Sabit fiyat — büyük ve küçük araç seçenekleri</li>\n<li>Uçuş takibi ile gerçek zamanlı karşılama</li>\n<li>Beldibi, Göynük, Tekirova, Çamyuva ve Kiriş bölgelerine servis</li>\n</ul>\n<h3>Şehirlerarası Otobüs</h3>\n<p>Antalya otogarından Kemer''e düzenli sefer mevcuttur ancak havalimanından otogar''a ayrıca ulaşmanız gerekmekte, bu da toplam seyahat süresini 2,5-3 saate çıkarmaktadır.</p>\n<h2>Kemer''e Yakın Bölgeler</h2>\n<p>Kemer merkezine ek olarak Beldibi, Göynük, Tekirova, Çamyuva, Kiriş ve Adrasan bölgelerine de transfer hizmeti sunulmaktadır.</p>\n<h2>Sık Sorulan Sorular</h2>\n<h3>Kemer''de araç kiralamak mantıklı mı?</h3>\n<p>Kemer ve çevresini keşfetmek isteyenler için araç kiralama iyi bir seçenek olabilir. Ancak otelinize ulaşmak için havalimanı transferi en pratik çözümdür.</p>\n<h3>Phaselis ve Olympos''a transfer var mı?</h3>\n<p>Evet, TORVIAN Transfer Kemer bölgesindeki antik sitelere ve kamp alanlarına özel transfer hizmeti sunmaktadır.</p>',

  E'<h2>Distance Between Antalya Airport and Kemer</h2>\n<p>The distance from Antalya Airport to Kemer is around 43 km, but as the route passes through mountainous terrain, travel time varies between <strong>40-55 minutes</strong>. Nestled at the foot of the Taurus Mountains on the Mediterranean coast, Kemer offers unique holiday experiences with the ancient city of Phaselis, Olympos and nature trails.</p>\n<h2>Transfer Options</h2>\n<h3>Private Transfer (Best Option)</h3>\n<p>Door-to-door service directly from the airport to your hotel. Enjoy the mountain scenery without any transport worries. With TORVIAN Transfer:</p>\n<ul>\n<li>Fixed price — options for small and large vehicles</li>\n<li>Real-time meet & greet with flight tracking</li>\n<li>Service to Beldibi, Göynük, Tekirova, Çamyuva and Kiriş</li>\n</ul>\n<h3>Intercity Bus</h3>\n<p>Regular services run from Antalya bus station to Kemer, but you still need to get from the airport to the bus station, bringing total travel time to 2.5-3 hours.</p>\n<h2>Areas Near Kemer</h2>\n<p>In addition to Kemer centre, transfers are available to Beldibi, Göynük, Tekirova, Çamyuva, Kiriş and Adrasan.</p>',

  E'<h2>Entfernung zwischen Flughafen Antalya und Kemer</h2>\n<p>Die Entfernung vom Flughafen Antalya nach Kemer beträgt etwa 43 km. Da die Route durch bergiges Gelände führt, variiert die Reisezeit zwischen <strong>40-55 Minuten</strong>. Kemer liegt am Fuß des Taurusgebirges an der Mittelmeerküste und bietet einzigartige Urlaubserlebnisse.</p>\n<h2>Transferoptionen</h2>\n<h3>Privater Transfer (Beste Option)</h3>\n<p>Tür-zu-Tür-Service direkt vom Flughafen zu Ihrem Hotel. Genießen Sie die Berglandschaft ohne Transportprobleme. Mit TORVIAN Transfer erhalten Sie Festpreise, Echtzeit-Empfang mit Flugverfolgung und Service nach Beldibi, Göynük, Tekirova, Çamyuva und Kiriş.</p>',

  E'<h2>Odległość między lotniskiem Antalya a Kemer</h2>\n<p>Odległość z lotniska Antalya do Kemer wynosi około 43 km. Ponieważ trasa prowadzi przez górski teren, czas podróży wynosi od <strong>40 do 55 minut</strong>. Kemer leży u stóp Gór Taurus nad Morzem Śródziemnym i oferuje wyjątkowe doświadczenia wakacyjne.</p>\n<h2>Opcje transferu</h2>\n<h3>Prywatny transfer (najlepsza opcja)</h3>\n<p>Usługa door-to-door bezpośrednio z lotniska do hotelu. Z TORVIAN Transfer: stała cena, spotkanie w czasie rzeczywistym ze śledzeniem lotu, obsługa Beldibi, Göynük, Tekirova, Çamyuva i Kiriş.</p>',

  E'<h2>Расстояние между аэропортом Анталии и Кемером</h2>\n<p>Расстояние от аэропорта Анталии до Кемера составляет около 43 км. Поскольку маршрут проходит через горную местность, время в пути варьируется от <strong>40 до 55 минут</strong>. Кемер расположен у подножия Таврских гор на берегу Средиземного моря.</p>\n<h2>Варианты трансфера</h2>\n<h3>Частный трансфер (лучший вариант)</h3>\n<p>Услуга от двери до двери прямо из аэропорта в отель. С TORVIAN Transfer: фиксированная цена, встреча в реальном времени с отслеживанием рейса, обслуживание Белдиби, Гёйнюк, Текирова, Чамьюва и Кириш.</p>',

  '/images/regions/kemer-coast.webp',
  true,
  NOW()
)
ON CONFLICT (slug) DO NOTHING;
