-- =============================================
-- TORVIAN TRANSFER — Region Descriptions (SEO)
-- 2026-06-20
--
-- Adds keyword-rich descriptions for EN / TR / DE / PL
-- for the 6 most popular regions.
--
-- IMPORTANT: Adding DE + PL descriptions also makes those locale
-- pages indexable (getTranslatedLocales() in page.tsx checks
-- description_{locale} — empty = noindex). These updates unlock
-- German and Polish organic traffic for these regions.
--
-- Keyword sources: Google Trends (Jun 2026)
--   GB/EN: "transfer from antalya airport" #1, "private transfer antalya airport" +8%
--          "antalya airport to belek/alanya/side" top queries
--   DE:    "hotel transfer antalya" #1 (+8%), "vip transfer antalya" +30%
--          "privattransfer antalya" +30%, "flughafentransfer antalya" +20%
--   Worldwide: "hotel transfer antalya" +20%, "antalya alanya transfer" +10%
--   PL:    "transfer antalya alanya" top query
-- =============================================

-- ===== ALANYA =====
UPDATE regions SET
  description_en = 'Alanya is a vibrant coastal city on the eastern Turkish Riviera, approximately 132 km east of Antalya Airport (AYT) — about 1 hour 45 minutes by private transfer. Since Alanya has no commercial airport, every tourist travelling to Alanya arrives via Antalya Airport (AYT), making the transfer from Antalya Airport to Alanya the most essential leg of the journey. Famous for Alanya Castle perched over the Mediterranean, Cleopatra Beach, the Red Tower, and the Damlataş Cave, Alanya is one of Turkey''s most visited summer destinations. TORVIAN provides direct private transfers from Antalya Airport to Alanya — hotel transfer included, door-to-door, fixed price, 24/7.',
  description_tr = 'Alanya, Antalya Havalimanı''nın (AYT) yaklaşık 132 km doğusunda yer alan, Doğu Türk Rivierası''nın en canlı sahil şehirlerinden biridir; özel VIP transfer ile yaklaşık 1 saat 45 dakikada ulaşılır. Alanya''nın kendine ait ticari bir havalimanı bulunmadığından, Alanya''ya seyahat eden her turist Antalya Havalimanı üzerinden gelir ve Antalya Havalimanı''ndan Alanya''ya transfer bu yolculuğun en kritik parçası haline gelir. Akdeniz manzarasına hâkim Alanya Kalesi, Kleopatra Plajı, Kızılkule ve Damlataş Mağarası ile Alanya her yıl milyonlarca turisti ağırlar. TORVIAN, Antalya Havalimanı''ndan Alanya''ya doğrudan kapıdan kapıya sabit fiyatlı özel transfer hizmeti sunar — 7/24.',
  description_de = 'Antalya Flughafentransfer nach Alanya: ca. 132 km östlich vom Flughafen Antalya (AYT), etwa 1 Stunde 45 Minuten Fahrtzeit mit privatem VIP Transfer. Da Alanya keinen eigenen Flughafen hat, reisen alle Touristen über den Flughafen Antalya ein — der Privattransfer Antalya–Alanya ist damit die wichtigste Transferstrecke der Riviera. Bekannt für die Alanya-Burg, den Kleopatrastrand und den Roten Turm. TORVIAN bietet direkten Hotel Transfer Antalya→Alanya: VIP Transfer Antalya Festpreis, Tür-zu-Tür, 24/7.',
  description_pl = 'Transfer z lotniska Antalya do Alanji: ok. 132 km na wschód od lotniska Antalya (AYT), ok. 1 godz. 45 min prywatnym transferem VIP. Ponieważ Alanya nie ma własnego lotniska, wszyscy turyści przylatują przez lotnisko Antalya — transfer z lotniska Antalya do Alanji jest niezbędnym etapem podróży. TORVIAN oferuje bezpośredni prywatny transfer z lotniska Antalya do każdego hotelu w Alanyi — stała cena, od drzwi do drzwi, 24/7.'
WHERE slug = 'alanya';

-- ===== BELEK =====
UPDATE regions SET
  description_en = 'Belek is Turkey''s premier golf and luxury resort destination, just 35 km east of Antalya Airport (AYT) — approximately 30 minutes by private transfer. The transfer from Antalya Airport to Belek is the most frequent airport transfer route for golfers flying into Antalya. Home to more than 20 championship golf courses and Turkey''s highest concentration of five-star hotels — including Cornelia, Ela Quality, Regnum Carya, Gloria, and Titanic Deluxe — Belek attracts golfers, families, and luxury travellers from across Europe. TORVIAN provides direct hotel transfer from Antalya Airport to Belek: private VIP, fixed price, no shuttle stops, 24/7.',
  description_tr = 'Belek, Antalya Havalimanı''nın (AYT) 35 km doğusunda, özel VIP transfer ile yaklaşık 30 dakika uzaklıkta yer alan Türkiye''nin en prestijli golf ve lüks tatil destinasyonudur. Antalya Havalimanı''ndan Belek''e transfer, Antalya''ya golf için gelen yolcular arasında en sık kullanılan havalimanı transfer güzergahıdır. Cornelia, Ela Quality, Regnum Carya, Gloria ve Titanic Deluxe dahil 20''den fazla şampiyona golf sahası ve Türkiye''nin en yoğun beş yıldızlı otel konsantrasyonuna ev sahipliği yapan Belek; her yıl Avrupalı golf tutkunlarını ve aile tatilcilerini ağırlar. TORVIAN, Antalya Havalimanı''ndan Belek''e doğrudan özel VIP transfer sunar — sabit fiyat, durak yok, 7/24.',
  description_de = 'Hotel Transfer Antalya nach Belek: Türkiyes führendes Golf- und Luxusreiseziel, nur 35 km östlich vom Flughafen Antalya (AYT) — ca. 30 Minuten Flughafentransfer Antalya–Belek. Mehr als 20 Golfplätze in Meisterschaftsqualität: Cornelia, Ela Quality, Regnum Carya, Gloria, Titanic Deluxe. TORVIAN: Privattransfer Antalya nach Belek — VIP Transfer Antalya Festpreis, kein Shuttle-Stopp, 24/7.',
  description_pl = 'Transfer z lotniska Antalya do Belek: 35 km od lotniska Antalya (AYT) — ok. 30 min prywatnym transferem VIP. Turcja''s najlepszy cel golfa i luksusowych wczasów: Cornelia, Ela Quality, Regnum Carya, Gloria, Titanic Deluxe — ponad 20 pól golfowych. TORVIAN: bezpośredni transfer z lotniska Antalya do Belek, stała cena, bez przystanków, 24/7.'
WHERE slug = 'belek';

-- ===== KEMER =====
UPDATE regions SET
  description_en = 'Kemer is a scenic resort town 45 km southwest of Antalya Airport (AYT), approximately 40 minutes by private transfer from Antalya Airport. The Kemer district includes Beldibi, Göynük, Çamyuva, Tekirova, and Adrasan — all reached in a single direct private transfer from Antalya Airport, no vehicle changes. Nestled between the Taurus Mountains and the Mediterranean, Kemer offers everything from lively all-inclusive resorts to secluded nature retreats. Kemer is also the starting point for Phaselis ancient ruins. TORVIAN private transfers cover all Kemer sub-districts directly from Antalya Airport — fixed price, door-to-door, 24/7.',
  description_tr = 'Kemer, Antalya Havalimanı''nın (AYT) 45 km güneybatısında, Antalya Havalimanı''ndan yaklaşık 40 dakika uzaklıkta yer alan eşsiz manzaralı bir tatil kasabasıdır. Kemer ilçesi; Beldibi, Göynük, Çamyuva, Tekirova ve Adrasan''ı kapsar; tüm bu noktalar Antalya Havalimanı''ndan tek direkt özel transfer ile ulaşılabilir, araç değişikliği yoktur. Toroslar ile Akdeniz arasına sıkışmış Kemer, canlı hepsi dahil tesislerden sakin doğa inzivalarına kadar geniş bir yelpaze sunar. TORVIAN, Antalya Havalimanı''ndan tüm Kemer alt bölgelerine doğrudan özel VIP transfer sunar — sabit fiyat, 7/24.',
  description_de = 'Privattransfer Antalya nach Kemer: 45 km südwestlich vom Flughafen Antalya (AYT) — ca. 40 Minuten Flughafentransfer. TORVIAN bedient alle Kemer-Teilorte direkt: Beldibi, Göynük, Çamyuva, Tekirova, Adrasan — ein einziger Direkttransfer, kein Fahrzeugwechsel. Zwischen Taurusgebirge und Mittelmeer gelegen: All-inclusive-Resorts, Boutique-Hotels, Phaselis-Ruinen. Hotel Transfer Antalya Kemer: VIP Transfer Antalya, Festpreis, 24/7.',
  description_pl = 'Transfer z lotniska Antalya do Kemer: 45 km na południowy zachód od lotniska Antalya (AYT) — ok. 40 min prywatnym transferem. TORVIAN obsługuje wszystkie miejscowości Kemer bezpośrednio: Beldibi, Göynük, Çamyuva, Tekirova, Adrasan — jeden bezpośredni przejazd, bez przesiadek. Stała cena, od drzwi do drzwi, 24/7.'
WHERE slug = 'kemer';

-- ===== SIDE =====
UPDATE regions SET
  description_en = 'Side is an ancient port city on a Mediterranean peninsula 75 km east of Antalya Airport (AYT), approximately 1 hour 10 minutes by private transfer. The transfer from Antalya Airport to Side is a popular route — the Antalya to Side transfer time of around 70 minutes in a private vehicle is far quicker than shuttle alternatives. Side is renowned for the 2nd-century Temple of Apollo on the seafront, a well-preserved Roman theatre, and long sandy beaches. The Side area covers Manavgat, Çolakli, Evrenseki, Kızılağaç, and Titreyengöl — all served by TORVIAN in a single direct airport transfer, fixed price, 24/7.',
  description_tr = 'Side, Antalya Havalimanı''nın (AYT) 75 km doğusunda, özel transfer ile yaklaşık 1 saat 10 dakika mesafede bir Akdeniz yarımadasına kurulu antik bir liman kentidir. Antalya Havalimanı''ndan Side''ye transfer popüler bir güzergahtır; özel araçla yaklaşık 70 dakika süren Antalya-Side transfer süresi servis alternatiflerine kıyasla çok daha hızlıdır. Side, sahil kenarındaki 2. yüzyıl Apollon Tapınağı, Roma tiyatrosu ve uzun kumsalları ile ünlüdür. Side bölgesi; Manavgat, Çolakli, Evrenseki, Kızılağaç ve Titreyengöl''ü kapsar — tümü TORVIAN tarafından sabit fiyatlı özel transfer ile servis edilir.',
  description_de = 'Flughafentransfer Antalya nach Side: antike Hafenstadt auf einer Mittelmeer-Halbinsel, 75 km östlich vom Flughafen Antalya (AYT) — ca. 1 Stunde 10 Minuten Fahrzeit. Die Antalya–Side Transferzeit von ca. 70 Minuten im Privattransfer ist deutlich schneller als Shuttle-Alternativen. Apollo-Tempel aus dem 2. Jh., römisches Theater, Sandstrände. TORVIAN: Hotel Transfer Antalya Side + Manavgat, Çolakli, Evrenseki, Kızılağaç, Titreyengöl — VIP Transfer Antalya, Festpreis, 24/7.',
  description_pl = 'Transfer z lotniska Antalya do Side: antyczne miasto portowe, 75 km na wschód od lotniska Antalya (AYT) — ok. 1 godz. 10 min prywatnym transferem. Słynne ze Świątyni Apollona i plaż. TORVIAN obsługuje cały region Side: Manavgat, Çolakli, Evrenseki, Kızılağaç, Titreyengöl — bezpośredni transfer, stała cena, 24/7.'
WHERE slug = 'side';

-- ===== LARA =====
UPDATE regions SET
  description_en = 'Lara is Antalya''s most prestigious hotel district, just 15–20 km east of Antalya Airport (AYT) — only 15 minutes by private transfer, the closest major resort zone to the terminal. The hotel transfer from Antalya Airport to Lara is the highest-volume airport transfer route in the entire Antalya region. The Lara beachfront strip is home to Turkey''s most spectacular mega-resorts: Titanic Mardan Palace, Rixos Premium Antalya, Delphin Imperial, Miracle Resort, and Calista Luxury Resort. With over a hundred four- and five-star properties, Lara generates more private transfer journeys from Antalya Airport than any other district. TORVIAN: direct hotel transfer from AYT to Lara — name-board meet & greet, fixed price, 24/7.',
  description_tr = 'Lara, Antalya Havalimanı''na (AYT) en yakın büyük tatil bölgesi olup havalimanının yalnızca 15–20 km doğusunda yer alır; özel VIP transfer ile yalnızca 15 dakika uzaklıktadır. Antalya Havalimanı''ndan Lara''ya otel transferi, tüm Antalya bölgesindeki en yüksek hacimli havalimanı transfer güzergahıdır. Türkiye''nin en görkemli mega-resort''larına ev sahipliği yapan Lara şeridinde Titanic Mardan Palace, Rixos Premium Antalya, Delphin Imperial, Miracle Resort ve Calista Luxury Resort bulunur. TORVIAN, AYT''den Lara''ya isimlikle karşılama, sabit fiyat ve 7/24 doğrudan otel transferi sunar.',
  description_de = 'Hotel Transfer Antalya Lara: nur 15–20 km östlich vom Flughafen Antalya (AYT) — ca. 15 Minuten Flughafentransfer, das am nächsten gelegene große Feriengebiet am Terminal. Lara ist der volumenstärkste Privattransfer Antalya-Korridor überhaupt: Titanic Mardan Palace, Rixos Premium Antalya, Delphin Imperial, Miracle Resort, Calista Luxury Resort — über 100 Vier- und Fünf-Sterne-Hotels. TORVIAN: VIP Transfer Antalya Lara, Namensschild-Empfang, Festpreis, 24/7.',
  description_pl = 'Transfer z lotniska Antalya do dzielnicy hotelowej Lara: tylko 15–20 km na wschód od lotniska Antalya (AYT) — ok. 15 min prywatnym transferem, najbliższa duża strefa kurortowa. Tutaj znajdują się: Titanic Mardan Palace, Rixos Premium Antalya, Delphin Imperial, Miracle Resort, Calista Luxury Resort — ponad 100 hoteli cztery i pięć gwiazdek. TORVIAN: bezpośredni transfer hotelowy z AYT do Lary, powitanie z tabliczką, stała cena, 24/7.'
WHERE slug = 'lara';

-- ===== KUNDU =====
UPDATE regions SET
  description_en = 'Kundu is a resort zone immediately adjacent to Lara, approximately 18 km east of Antalya Airport (AYT) and reachable in around 20 minutes by private transfer. Sharing the same long golden beach as Lara, Kundu is home to large all-inclusive resort complexes popular with European families and groups. TORVIAN serves both Lara and Kundu in a single direct hotel transfer from Antalya Airport — private VIP, name-board meet & greet at arrivals, fixed price, 24/7.',
  description_tr = 'Kundu, Lara''ya hemen komşu bir tatil bölgesi olup Antalya Havalimanı''nın (AYT) yaklaşık 18 km doğusunda yer alır ve özel VIP transfer ile yaklaşık 20 dakikada ulaşılır. Lara ile aynı uzun altın kumsalı paylaşan Kundu''da hepsi dahil tatil yapan Avrupalı aileler arasında popüler büyük resort kompleksleri bulunmaktadır. TORVIAN, hem Lara hem Kundu''ya Antalya Havalimanı''ndan tek direkt otel transferi sunar — isimlikle karşılama, sabit fiyat, 7/24.',
  description_de = 'Hotel Transfer Antalya Kundu: direkt neben Lara, ca. 18 km östlich vom Flughafen Antalya (AYT) — rund 20 Minuten Privattransfer Antalya. Große All-inclusive-Resorts, beliebt bei europäischen Familien. TORVIAN bedient Lara und Kundu gemeinsam in einem VIP Transfer Antalya: Namensschild-Empfang, Festpreis, 24/7.',
  description_pl = 'Transfer z lotniska Antalya do Kundu: sąsiaduje z Larą, ok. 18 km na wschód od lotniska Antalya (AYT) — ok. 20 min prywatnym transferem. Duże kompleksy all-inclusive popularne wśród europejskich rodzin. TORVIAN obsługuje Larę i Kundu wspólnie w jednym bezpośrednim transferze hotelowym z AYT, stała cena, 24/7.'
WHERE slug = 'kundu';
