-- =============================================
-- TORVIAN TRANSFER — Region Descriptions (SEO)
-- 2026-06-20
--
-- Adds keyword-rich, natural-language descriptions
-- (EN / TR / DE) for the most popular regions.
-- PL and RU fall back to the translated aboutDescDefault.
-- =============================================

-- ===== ALANYA =====
UPDATE regions SET
  description_en = 'Alanya is a vibrant coastal city on the eastern Turkish Riviera, approximately 132 km east of Antalya Airport (AYT) — about 1 hour 45 minutes by private VIP transfer. Famous for Alanya Castle perched over the Mediterranean, Cleopatra Beach, the Red Tower, and the Damlataş Cave, Alanya is one of Turkey''s most visited summer destinations. Since Alanya has no commercial airport of its own, virtually every visitor arrives via Antalya Airport — making a reliable airport transfer essential. TORVIAN provides direct, fixed-price private transfers from the AYT arrivals hall straight to any hotel in Alanya, Mahmutlar, Oba, or Kestel, 24 hours a day.',
  description_tr = 'Alanya, Antalya Havalimanı''nın (AYT) yaklaşık 132 km doğusunda yer alan, Doğu Türk Rivierası''nın en canlı sahil şehirlerinden biridir; özel VIP transfer ile yaklaşık 1 saat 45 dakikada ulaşılır. Akdeniz manzarasına hâkim Alanya Kalesi, Kleopatra Plajı, Kızılkule ve Damlataş Mağarası ile her yıl milyonlarca turisti ağırlayan Alanya''nın kendine ait ticari bir havalimanı bulunmadığından ziyaretçilerin tamamına yakını Antalya Havalimanı üzerinden gelir. TORVIAN, AYT varış salonundan Alanya, Mahmutlar, Oba ve Kestel''deki her otele 7/24 sabit fiyatlı özel transfer hizmeti sunar.',
  description_de = 'Alanya ist eine lebhafte Küstenstadt an der östlichen Türkischen Riviera, ca. 132 km östlich vom Flughafen Antalya (AYT) — etwa 1 Stunde 45 Minuten mit dem privaten VIP-Transfer. Bekannt für die über dem Mittelmeer thronende Alanya-Burg, den Kleopatrastrand, den Roten Turm und die Damlataş-Höhle, empfängt Alanya jährlich Millionen Touristen. Da Alanya keinen eigenen Flughafen hat, reisen nahezu alle Besucher über den Flughafen Antalya ein — ein zuverlässiger Airport Transfer ist daher unverzichtbar. TORVIAN bietet direkten Festpreistransfer vom AYT zu jedem Hotel in Alanya, Mahmutlar, Oba und Kestel — 24/7.'
WHERE slug = 'alanya';

-- ===== BELEK =====
UPDATE regions SET
  description_en = 'Belek is Turkey''s premier golf and luxury resort destination, just 35 km east of Antalya Airport (AYT) — approximately 30 minutes by private VIP transfer. Home to more than 20 championship golf courses and Turkey''s highest concentration of five-star hotels — including Cornelia, Ela Quality, Regnum Carya, Gloria, and Titanic Deluxe — Belek attracts golfers, families, and luxury travellers from across Europe. Every year tens of thousands of golfers fly into Antalya Airport specifically for Belek''s courses. TORVIAN provides direct, fixed-price airport-to-hotel transfers for all Belek and Kadriye properties, with no shuttle stops and no meter running.',
  description_tr = 'Belek, Antalya Havalimanı''nın (AYT) 35 km doğusunda, özel VIP transfer ile yaklaşık 30 dakika uzaklıkta yer alan Türkiye''nin en prestijli golf ve lüks tatil destinasyonudur. Cornelia, Ela Quality, Regnum Carya, Gloria ve Titanic Deluxe dahil 20''den fazla şampiyona golf sahası ve Türkiye''nin en yoğun beş yıldızlı otel konsantrasyonuna ev sahipliği yapan Belek, her yıl Avrupalı golf tutkunlarını ve aile tatilcilerini ağırlar. Yüksek sezonda binlerce golfçü Antalya Havalimanı''na özellikle Belek sahalarını oynamak için iner. TORVIAN, AYT''den Belek ve Kadriye''deki tüm otellere sabit fiyatlı özel transfer sunar; durak yok, sayaç yok.',
  description_de = 'Belek ist Türkiyes führendes Golf- und Luxusreiseziel, nur 35 km östlich vom Flughafen Antalya (AYT) — ca. 30 Minuten mit dem privaten VIP-Transfer. Mit über 20 Meisterschaftsgolfplätzen und der höchsten Dichte an Fünf-Sterne-Hotels in der Türkei — darunter Cornelia, Ela Quality, Regnum Carya, Gloria und Titanic Deluxe — zieht Belek jährlich Hunderttausende Golfer und Familien aus ganz Europa an. TORVIAN bringt Sie direkt vom Flughafen Antalya zu Ihrem Hotel in Belek oder Kadriye — ohne Shuttle-Stopps, zum Festpreis, jederzeit.'
WHERE slug = 'belek';

-- ===== KEMER =====
UPDATE regions SET
  description_en = 'Kemer is a scenic resort town 45 km southwest of Antalya Airport (AYT), nestled between the Taurus Mountains and the Mediterranean Sea — approximately 40 minutes by private VIP transfer. The broader Kemer district includes Beldibi, Göynük, Çamyuva, Tekirova, and Adrasan, each with its own character: lively all-inclusive resorts, secluded pine-forest retreats, and the charming harbour town of Kemer itself. Kemer is also the gateway to Phaselis, one of Turkey''s best-preserved ancient Lycian cities. TORVIAN covers all Kemer sub-districts in a single direct drive from Antalya Airport — no vehicle changes, no shared stops.',
  description_tr = 'Kemer, Antalya Havalimanı''nın (AYT) 45 km güneybatısında, Toroslar ile Akdeniz arasına sıkışmış eşsiz manzaralı bir tatil kasabasıdır; özel VIP transfer ile yaklaşık 40 dakika uzaklıktadır. Geniş Kemer ilçesi; Beldibi, Göynük, Çamyuva, Tekirova ve Adrasan alt bölgelerini kapsar: canlı hepsi dahil tesislerden çam ormanlarıyla çevrili butik otellere, tarihi Kemer limanı''na kadar geniş bir yelpaze sunar. Kemer, Türkiye''nin en iyi korunmuş Likya antik kenti Phaselis''e de kapı aralayan bir noktadır. TORVIAN, Antalya Havalimanı''ndan tüm Kemer alt bölgelerine tek ve direkt bir sürüşle ulaşım sağlar.',
  description_de = 'Kemer ist ein malerischer Ferienort 45 km südwestlich vom Flughafen Antalya (AYT), eingebettet zwischen dem Taurusgebirge und dem Mittelmeer — ca. 40 Minuten mit dem privaten VIP-Transfer. Der Kemer-Bezirk umfasst Beldibi, Göynük, Çamyuva, Tekirova und Adrasan — von lebhaften All-inclusive-Resorts über Boutique-Naturhotels im Kiefernwald bis zum charmanten Hafenstädtchen Kemer selbst. Kemer ist auch das Tor zu Phaselis, einer der besterhaltenen antiken Lykischen Städte der Türkei. TORVIAN befördert Sie in einer einzigen Direktfahrt vom Flughafen Antalya zu jedem Hotel im gesamten Kemer-Bezirk.'
WHERE slug = 'kemer';

-- ===== SIDE =====
UPDATE regions SET
  description_en = 'Side is an ancient port city on a Mediterranean peninsula 75 km east of Antalya Airport (AYT), approximately 1 hour 10 minutes by private VIP transfer. Renowned for its remarkable 2nd-century Temple of Apollo standing right on the seafront, a well-preserved Roman theatre, and long sandy beaches backed by pine forests, Side attracts history enthusiasts and beach lovers alike. The broader Side area includes Manavgat, Çolakli, Evrenseki, Kızılağaç, and Titreyengöl — all served in a single direct private transfer from AYT. TORVIAN covers every hotel and villa in the Side region with a fixed-price journey from the airport.',
  description_tr = 'Side, Antalya Havalimanı''nın (AYT) 75 km doğusunda, özel VIP transfer ile yaklaşık 1 saat 10 dakika mesafede bir Akdeniz yarımadasına kurulu antik bir liman kentidir. Sahil kenarında yükselen eşsiz 2. yüzyıl Apollon Tapınağı, iyi korunmuş Roma tiyatrosu ve çam ormanlarıyla çerçevelenmiş uzun kumsalları ile Side; tarih meraklılarını ve plaj severlerini eşit ölçüde büyüler. Geniş Side bölgesi; Manavgat şehir merkezi, Çolakli, Evrenseki, Kızılağaç ve Titreyengöl''ü kapsar ve tümü AYT''den tek direkt sürüşle servis edilir. TORVIAN, Side bölgesindeki her otel ve villaya sabit fiyatlı kapıdan kapıya transfer sunar.',
  description_de = 'Side ist eine antike Hafenstadt auf einer Mittelmeer-Halbinsel, 75 km östlich vom Flughafen Antalya (AYT) — ca. 1 Stunde 10 Minuten mit dem privaten VIP-Transfer. Bekannt für den direkt am Meer stehenden Apollo-Tempel aus dem 2. Jahrhundert, ein gut erhaltenes römisches Theater und lange Sandstrände vor Kiefernwäldern, zieht Side Geschichtsbegeisterte und Strandliebhaber gleichermaßen an. Die Region umfasst Manavgat, Çolakli, Evrenseki, Kızılağaç und Titreyengöl — alles in einer einzigen direkten Privatfahrt vom AYT. TORVIAN bedient jedes Hotel und jede Villa im Side-Gebiet mit einer Festpreisfahrt.'
WHERE slug = 'side';

-- ===== LARA =====
UPDATE regions SET
  description_en = 'Lara is Antalya''s most prestigious hotel district, just 15–20 km east of Antalya Airport (AYT) — only 15 minutes by private VIP transfer, making it the closest major resort zone to the terminal. The Lara beachfront strip is home to some of Turkey''s most spectacular mega-resorts: Titanic Mardan Palace, Rixos Premium Antalya, Delphin Imperial, Miracle Resort, and Calista Luxury Resort. With over a hundred four-star and five-star properties, Lara generates more airport transfer journeys than any other Antalya district. TORVIAN provides direct, name-board meet-and-greet transfers from the AYT arrivals hall to any Lara hotel — 24 hours a day, fixed price.',
  description_tr = 'Lara, Antalya Havalimanı''na (AYT) en yakın büyük tatil bölgesi olup havalimanının yalnızca 15–20 km doğusunda yer alır; özel VIP transfer ile yalnızca 15 dakika uzaklıktadır. Lara sahil şeridinde Türkiye''nin en görkemli mega-resort''larından bazıları bulunmaktadır: Titanic Mardan Palace, Rixos Premium Antalya, Delphin Imperial, Miracle Resort ve Calista Luxury Resort bunların başında gelir. Yüzden fazla dört yıldızlı ve beş yıldızlı tesisi bünyesinde barındıran Lara, diğer Antalya bölgelerine kıyasla en yüksek havalimanı transfer trafiğini oluşturur. TORVIAN, gündüz veya gece AYT varış salonundan Lara''daki her otele isimlikle karşılama ve sabit fiyatlı özel transfer sunar.',
  description_de = 'Lara ist Antalyas prestigeträchtigstes Hotelviertel, nur 15–20 km östlich vom Flughafen Antalya (AYT) — ca. 15 Minuten mit dem privaten VIP-Transfer und damit das am nächsten gelegene große Feriengebiet am Terminal. Die Lara-Strandpromenade beherbergt einige der spektakulärsten Mega-Resorts der Türkei: Titanic Mardan Palace, Rixos Premium Antalya, Delphin Imperial, Miracle Resort und Calista Luxury Resort. Mit über hundert Vier- und Fünf-Sterne-Hotels verzeichnet Lara das höchste Flughafen-Transferaufkommen aller Antalya-Regionen. TORVIAN bietet direkten Transfer mit Namensschild-Empfang vom AYT zu jedem Lara-Hotel — rund um die Uhr, Festpreis.'
WHERE slug = 'lara';

-- ===== KUNDU =====
UPDATE regions SET
  description_en = 'Kundu is a resort zone immediately adjacent to Lara, approximately 18 km east of Antalya Airport (AYT) and reachable in around 20 minutes by private VIP transfer. Sharing the same long golden beach as Lara, Kundu is home to large resort complexes that are popular with European families and groups on all-inclusive holidays. The Lara–Kundu corridor is the fastest-growing hotel zone in Antalya, with new luxury properties opening every season. TORVIAN serves both Lara and Kundu hotels from Antalya Airport in a single direct transfer, with name-board meet & greet at arrivals.',
  description_tr = 'Kundu, Lara''ya hemen komşu bir tatil bölgesi olup Antalya Havalimanı''nın (AYT) yaklaşık 18 km doğusunda yer alır ve özel VIP transfer ile yaklaşık 20 dakikada ulaşılır. Lara ile aynı uzun altın kumsalı paylaşan Kundu''da hepsi dahil tatil yapan Avrupalı aileler ve gruplar arasında popüler büyük resort kompleksleri bulunmaktadır. Lara–Kundu koridoru, her sezon yeni lüks tesislerin kapılarını açmasıyla Antalya''nın en hızlı büyüyen otel bölgesidir. TORVIAN, hem Lara hem Kundu''daki otellere AYT''den tek direkt transfer, varış salonunda isimlikle karşılama ve 7/24 hizmet sunar.',
  description_de = 'Kundu ist ein Feriengebiet direkt neben Lara, ca. 18 km östlich vom Flughafen Antalya (AYT) — in etwa 20 Minuten mit dem privaten VIP-Transfer erreichbar. Kundu teilt die gleiche lange Goldstrandküste wie Lara und beherbergt große Resortanlagen, die bei europäischen Familien und Gruppen für All-inclusive-Urlaube beliebt sind. Der Korridor Lara–Kundu ist Antalyas am schnellsten wachsendes Hotelgebiet. TORVIAN bedient Lara und Kundu in einem einzigen Direkttransfer vom Flughafen Antalya, mit Namensschild-Empfang in der Ankunftshalle, rund um die Uhr.'
WHERE slug = 'kundu';
