-- 044: Unique region copy — Belek/Side corridor + Antalya city, all 6 languages
--
-- Continues the programme started in 043. A region page is ~90% shared
-- template (FAQ, "Why TORVIAN", "How to book", comparison table all come from
-- src/messages/*.json with only {name} interpolated); `description_<locale>`
-- is the only block that makes it unique. Regions still carrying the
-- 120-character seed text read as near-duplicates to Google, which is why the
-- whole region set draws ~700 impressions against the blog's ~20,000.
--
-- Also note: for de/pl/ru/nl the region page marks itself noindex unless
-- description_<locale> or meta_title_<locale> is filled (see
-- getTranslatedLocales in src/app/[locale]/[region]/page.tsx, mirrored by
-- src/app/sitemap.ts). Writing these columns is what makes the page indexable
-- in those four languages at all.
--
-- DISTANCES — from supabase/seed.sql, the live regions data:
--   sehirici 12 km / 20 min · kadriye 30 km / 30 min
--   bogazkent 45 km / 40 min · evrenseki 60 km / 50 min
--   kizilagac 80 km / 70 min
--
-- KEYWORDS per market (Google Trends 12-month + this site's Search Console):
--   DE  "hotel transfer antalya" (69) · "transfer antalya flughafen" (100)
--   EN  "airport transfer antalya" (100) · "antalya private transfer" (23)
--   NL  English product phrase + Dutch prose (Trends NL: commercial intent
--       is typed in English, questions in Dutch)
--   PL  "transfer z lotniska antalya" · "odległość od lotniska"
--   RU  "трансфер аэропорт анталия" · "частный трансфер"
--   TR  "antalya havalimanı transfer"
--
-- Safe to re-run.


-- ===== KADRIYE — 30 km, 30 min =====
-- Commercially the most valuable region in this batch: The Land of Legends
-- theme park sits in Kadriye, and "land of legends transfer" is a commercial
-- query the site already ranks ~33 for.
UPDATE regions SET
  description_en = 'Kadriye is a resort village 30 km east of Antalya Airport (AYT), about 30 minutes away by private transfer. It sits between Belek and the coast and is home to The Land of Legends theme park as well as several of Turkey''s best-known golf resorts, including Regnum Carya and Maxx Royal. Most visitors here are families heading for the water park or golfers arriving with equipment, so luggage space matters — our Mercedes Vito takes five passengers plus large cases, and we confirm golf bags in advance. TORVIAN provides a private airport transfer from Antalya to any hotel, villa or golf resort in Kadriye: fixed price per vehicle, meet and greet with a name board, live flight tracking and 24/7 availability.',
  description_tr = 'Kadriye, Antalya Havalimanı''nın (AYT) 30 km doğusunda, özel transferle yaklaşık 30 dakika mesafede bir tatil beldesidir. Belek ile sahil arasında yer alır ve The Land of Legends tema parkına ev sahipliği yapar; ayrıca Regnum Carya ve Maxx Royal gibi Türkiye''nin en bilinen golf tesisleri buradadır. Bölgeye gelenlerin çoğu aquapark için gelen aileler veya ekipmanıyla seyahat eden golfçülerdir; bu yüzden bagaj hacmi önemlidir. Mercedes Vito araçlarımız beş yolcu ve büyük valizleri rahatça alır, golf çantası talebini önceden onaylarız. TORVIAN, Antalya Havalimanı''ndan Kadriye''deki her otele, villaya ve golf tesisine özel transfer sunar: araç başına sabit fiyat, isim tabelasıyla karşılama, canlı uçuş takibi, 7/24.',
  description_de = 'Hotel Transfer Antalya nach Kadriye: 30 km östlich vom Flughafen Antalya (AYT), rund 30 Minuten Fahrt mit dem Privattransfer. Der Ort liegt zwischen Belek und der Küste und beherbergt den Freizeitpark The Land of Legends sowie einige der bekanntesten Golfresorts der Türkei, darunter Regnum Carya und Maxx Royal. Die meisten Gäste sind Familien auf dem Weg zum Wasserpark oder Golfer mit Ausrüstung — Gepäckraum ist hier entscheidend. Unser Mercedes Vito fasst fünf Passagiere plus grosse Koffer, Golfbags bestätigen wir vorab. TORVIAN fährt Sie vom Flughafen Antalya direkt zu jedem Hotel oder Golfresort in Kadriye: Festpreis pro Fahrzeug, Abholung mit Namensschild, Flugverfolgung, 24/7.',
  description_pl = 'Kadriye to kurort 30 km na wschód od lotniska Antalya (AYT), około 30 minut prywatnym transferem. Leży między Belek a wybrzeżem i mieści park rozrywki The Land of Legends oraz jedne z najbardziej znanych pól golfowych Turcji, w tym Regnum Carya i Maxx Royal. Większość gości to rodziny jadące do parku wodnego albo golfiści ze sprzętem, więc miejsce na bagaż ma tu znaczenie. Nasz Mercedes Vito zabiera pięciu pasażerów i duże walizki, a torby golfowe potwierdzamy z wyprzedzeniem. TORVIAN oferuje prywatny transfer z lotniska Antalya do każdego hotelu, willi i resortu golfowego w Kadriye: stała cena za pojazd, powitanie z tabliczką, monitoring lotu, 24/7.',
  description_ru = 'Кадрие — курортный посёлок в 30 км к востоку от аэропорта Анталии (AYT), около 30 минут на частном трансфере. Он расположен между Белеком и морем; здесь находится парк развлечений The Land of Legends и несколько самых известных гольф-курортов Турции, включая Regnum Carya и Maxx Royal. Большинство гостей — семьи, едущие в аквапарк, и гольфисты с инвентарём, поэтому объём багажника здесь особенно важен. Mercedes Vito вмещает пять пассажиров и крупные чемоданы, гольф-сумки мы подтверждаем заранее. TORVIAN выполняет частный трансфер аэропорт Анталия — Кадрие до любого отеля, виллы или гольф-клуба: фиксированная цена за автомобиль, встреча с табличкой, отслеживание рейса, круглосуточно.',
  description_nl = 'Kadriye is een badplaats op 30 km ten oosten van de luchthaven Antalya (AYT), ongeveer 30 minuten met een privétransfer. Het ligt tussen Belek en de kust en herbergt het pretpark The Land of Legends en enkele van de bekendste golfresorts van Turkije, waaronder Regnum Carya en Maxx Royal. De meeste gasten zijn gezinnen op weg naar het waterpark of golfers met uitrusting, dus bagageruimte telt hier zwaar. Onze Mercedes Vito neemt vijf passagiers plus grote koffers mee; golftassen bevestigen wij vooraf. TORVIAN verzorgt een Antalya Airport transfer naar elk hotel, elke villa en elk golfresort in Kadriye: vaste prijs per voertuig, ontvangst met naambord, vluchtmonitoring, 24/7.'
WHERE slug = 'kadriye';


-- ===== BOĞAZKENT — 45 km, 40 min =====
UPDATE regions SET
  description_en = 'Boğazkent is a quiet beach village 45 km from Antalya Airport (AYT), roughly 40 minutes by private transfer. Sitting just east of Belek where the Acısu river meets the sea, it is backed by the Sorgun pine forest and has none of the nightlife of the bigger resorts — which is exactly why families and couples pick it. The all-inclusive hotels here sit directly on a long, uncrowded sand-and-shingle beach. Because Boğazkent is small and spread out, shared shuttles often drop passengers a walk from their hotel. TORVIAN drives door to door: private airport transfer from Antalya, fixed price per vehicle, name-board welcome, flight tracking and no night surcharge.',
  description_tr = 'Boğazkent, Antalya Havalimanı''na (AYT) 45 km uzaklıkta, özel transferle yaklaşık 40 dakika mesafede sakin bir sahil köyüdür. Belek''in hemen doğusunda, Acısu Deresi''nin denizle buluştuğu noktada yer alır; arkasında Sorgun çam ormanı uzanır. Büyük tatil merkezlerinin gece hayatı burada yoktur — aileler ve çiftler tam da bu yüzden Boğazkent''i seçer. Her şey dahil oteller uzun ve kalabalık olmayan kum-çakıl plajın hemen üzerindedir. Bölge küçük ve dağınık olduğundan grup servisleri yolcuyu çoğu zaman otelinden uzağa bırakır. TORVIAN kapıdan kapıya götürür: Antalya Havalimanı''ndan özel transfer, araç başına sabit fiyat, isim tabelasıyla karşılama, uçuş takibi ve gece zammı yok.',
  description_de = 'Boğazkent ist ein ruhiges Stranddorf 45 km vom Flughafen Antalya (AYT) entfernt, etwa 40 Minuten Fahrt mit dem Privattransfer. Es liegt östlich von Belek an der Mündung des Acısu ins Meer, im Rücken der Kiefernwald von Sorgun. Das Nachtleben der grossen Resorts fehlt hier völlig — genau deshalb wählen Familien und Paare diesen Ort. Die All-inclusive-Hotels stehen direkt an einem langen, wenig besuchten Sand-Kies-Strand. Weil Boğazkent klein und weitläufig ist, setzen Sammeltransfers Gäste oft ein Stück vom Hotel entfernt ab. TORVIAN fährt bis vor die Tür: Hotel Transfer Antalya zum Festpreis pro Fahrzeug, Abholung mit Namensschild, Flugverfolgung, ohne Nachtzuschlag.',
  description_pl = 'Boğazkent to spokojna nadmorska wioska 45 km od lotniska Antalya (AYT), około 40 minut prywatnym transferem. Leży tuż na wschód od Belek, w miejscu gdzie rzeka Acısu wpada do morza, a od tyłu osłania ją sosnowy las Sorgun. Nie ma tu życia nocnego większych kurortów — i właśnie dlatego wybierają je rodziny i pary. Hotele all inclusive stoją bezpośrednio przy długiej, mało zatłoczonej plaży. Ponieważ Boğazkent jest małe i rozciągnięte, transfery zbiorowe często wysadzają gości w sporej odległości od hotelu. TORVIAN dowozi pod same drzwi: prywatny transfer z lotniska Antalya, stała cena za pojazd, powitanie z tabliczką, monitoring lotu, bez dopłaty nocnej.',
  description_ru = 'Богазкент — тихая приморская деревня в 45 км от аэропорта Анталии (AYT), около 40 минут на частном трансфере. Она расположена сразу к востоку от Белека, в месте впадения реки Аджысу в море, а с суши её прикрывает сосновый лес Соргун. Ночной жизни крупных курортов здесь нет — именно поэтому Богазкент выбирают семьи и пары. Отели «всё включено» стоят прямо на длинном малолюдном песчано-галечном пляже. Посёлок небольшой и растянутый, поэтому групповые автобусы часто высаживают гостей далеко от отеля. TORVIAN довозит до двери: частный трансфер из аэропорта Анталии, фиксированная цена за машину, встреча с табличкой, отслеживание рейса, без ночной наценки.',
  description_nl = 'Boğazkent is een rustig stranddorp op 45 km van de luchthaven Antalya (AYT), ongeveer 40 minuten met een privétransfer. Het ligt net ten oosten van Belek, waar de rivier de Acısu in zee uitmondt, met het dennenbos van Sorgun in de rug. Het uitgaansleven van de grote badplaatsen ontbreekt hier volledig — precies daarom kiezen gezinnen en stellen voor Boğazkent. De all-inclusive hotels staan direct aan een lang, rustig zand- en kiezelstrand. Omdat het dorp klein en uitgestrekt is, zetten gedeelde shuttles gasten vaak een eind van hun hotel af. TORVIAN rijdt van deur tot deur: Antalya Airport transfer met vaste prijs per voertuig, ontvangst met naambord, vluchtmonitoring, geen nachttoeslag.'
WHERE slug = 'bogazkent';


-- ===== EVRENSEKI — 60 km, 50 min =====
UPDATE regions SET
  description_en = 'Evrenseki lies 60 km east of Antalya Airport (AYT), about 50 minutes by private transfer, on the coastal strip immediately west of Side. It is one of the densest hotel areas on this stretch of the Turkish Riviera: a long line of all-inclusive resorts facing a wide sandy beach, with the ancient city of Side and its seafront Temple of Apollo a short drive away. Many guests combine a beach holiday here with day trips to Side, Manavgat waterfall and Aspendos. Hotel entrances along the strip look alike and are easy to miss at night, so we ask for the exact hotel name at booking. TORVIAN runs a private airport transfer straight to the door: fixed price per vehicle, meet and greet, flight tracking, 24/7.',
  description_tr = 'Evrenseki, Antalya Havalimanı''nın (AYT) 60 km doğusunda, özel transferle yaklaşık 50 dakika mesafede, Side''nin hemen batısındaki sahil şeridinde yer alır. Türk Rivierası''nın bu bölümündeki en yoğun otel bölgelerinden biridir: geniş kumsala bakan uzun bir her şey dahil tesis dizisi ve kısa mesafede antik Side ile deniz kıyısındaki Apollon Tapınağı. Konukların çoğu buradaki plaj tatilini Side, Manavgat Şelalesi ve Aspendos gezileriyle birleştirir. Şerit boyunca otel girişleri birbirine benzer ve geceleri kolayca kaçırılır; bu yüzden rezervasyonda tam otel adını isteriz. TORVIAN doğrudan kapıya özel transfer yapar: araç başına sabit fiyat, karşılama, uçuş takibi, 7/24.',
  description_de = 'Evrenseki liegt 60 km östlich vom Flughafen Antalya (AYT), etwa 50 Minuten mit dem Privattransfer, auf dem Küstenstreifen direkt westlich von Side. Es ist eines der dichtesten Hotelgebiete dieses Abschnitts der Türkischen Riviera: eine lange Reihe von All-inclusive-Resorts an einem breiten Sandstrand, mit der antiken Stadt Side und dem Apollontempel am Meer nur wenige Fahrminuten entfernt. Viele Gäste verbinden den Strandurlaub mit Ausflügen nach Side, zum Manavgat-Wasserfall und nach Aspendos. Die Hoteleinfahrten entlang der Strandstrasse ähneln einander und sind nachts leicht zu übersehen — wir erfragen daher den genauen Hotelnamen. TORVIAN: Hotel Transfer Antalya bis vor die Tür, Festpreis, Flugverfolgung, 24/7.',
  description_pl = 'Evrenseki leży 60 km na wschód od lotniska Antalya (AYT), około 50 minut prywatnym transferem, na pasie wybrzeża tuż na zachód od Side. To jeden z najgęściej zabudowanych hotelami odcinków tej części Riwiery Tureckiej: długi ciąg resortów all inclusive przy szerokiej piaszczystej plaży, a starożytne Side ze świątynią Apolla nad morzem jest o kilka minut jazdy. Wielu gości łączy tu wypoczynek na plaży z wycieczkami do Side, na wodospad Manavgat i do Aspendos. Wjazdy do hoteli wzdłuż tej drogi wyglądają podobnie i nocą łatwo je przeoczyć, dlatego prosimy o dokładną nazwę hotelu. TORVIAN dowozi pod drzwi: stała cena za pojazd, powitanie z tabliczką, monitoring lotu, 24/7.',
  description_ru = 'Эвренсеки находится в 60 км к востоку от аэропорта Анталии (AYT), около 50 минут на частном трансфере, на прибрежной полосе сразу к западу от Сиде. Это один из самых плотно застроенных отелями участков этой части Турецкой Ривьеры: длинная линия отелей «всё включено» вдоль широкого песчаного пляжа, а античный Сиде с храмом Аполлона у самой воды — в нескольких минутах езды. Многие гости совмещают пляжный отдых с поездками в Сиде, на водопад Манавгат и в Аспендос. Въезды в отели вдоль этой дороги похожи друг на друга и ночью их легко пропустить, поэтому мы просим точное название отеля. TORVIAN везёт прямо к дверям: фиксированная цена за машину, встреча с табличкой, отслеживание рейса, круглосуточно.',
  description_nl = 'Evrenseki ligt 60 km ten oosten van de luchthaven Antalya (AYT), ongeveer 50 minuten met een privétransfer, op de kuststrook direct ten westen van Side. Het is een van de dichtstbebouwde hotelgebieden van dit deel van de Turkse Rivièra: een lange rij all-inclusive resorts aan een breed zandstrand, met de antieke stad Side en de Apollotempel aan zee op enkele minuten rijden. Veel gasten combineren het strand met uitstapjes naar Side, de Manavgat-waterval en Aspendos. De hotelopritten langs deze weg lijken op elkaar en zijn ''s avonds makkelijk te missen, dus vragen wij bij het boeken om de exacte hotelnaam. TORVIAN brengt u met een Antalya Airport transfer tot aan de deur: vaste prijs, vluchtmonitoring, 24/7.'
WHERE slug = 'evrenseki';


-- ===== KIZILAĞAÇ — 80 km, 1 h 10 min =====
UPDATE regions SET
  description_en = 'Kızılağaç is 80 km from Antalya Airport (AYT), about 1 hour 10 minutes by private transfer — the furthest point of the Side resort belt before the coast turns towards Alanya. It is quieter than Side itself: large all-inclusive hotels set back from a long beach, with the Titreyengöl pine forest and lagoon nearby and Manavgat town a few minutes inland. The extra distance is precisely why a private transfer pays off here; a shared shuttle covering the whole Side strip can add an hour or more of stops before it reaches Kızılağaç. TORVIAN drives direct: private airport transfer from Antalya, fixed price per vehicle, name-board welcome, live flight tracking, 24/7 with no night surcharge.',
  description_tr = 'Kızılağaç, Antalya Havalimanı''na (AYT) 80 km uzaklıkta, özel transferle yaklaşık 1 saat 10 dakika mesafededir — sahilin Alanya''ya döndüğü noktadan önceki Side otel kuşağının en uç bölgesidir. Side''nin kendisinden daha sakindir: uzun bir plajın gerisine kurulmuş büyük her şey dahil oteller, yakınında Titreyengöl çam ormanı ve lagünü, birkaç dakika içeride ise Manavgat ilçesi. Bu ek mesafe, burada özel transferin neden avantajlı olduğunu açıklar; tüm Side şeridini dolaşan grup servisi Kızılağaç''a varmadan bir saat veya daha fazla durak ekleyebilir. TORVIAN doğrudan gider: sabit fiyat, isim tabelasıyla karşılama, canlı uçuş takibi, 7/24, gece zammı yok.',
  description_de = 'Kızılağaç liegt 80 km vom Flughafen Antalya (AYT) entfernt, etwa 1 Stunde 10 Minuten mit dem Privattransfer — der äusserste Punkt des Hotelgürtels von Side, bevor die Küste Richtung Alanya abbiegt. Es ist ruhiger als Side selbst: grosse All-inclusive-Hotels etwas zurückgesetzt an einem langen Strand, in der Nähe der Kiefernwald und die Lagune von Titreyengöl, wenige Minuten landeinwärts die Stadt Manavgat. Gerade wegen der grösseren Entfernung lohnt sich hier der Privattransfer: Ein Sammelbus, der den gesamten Küstenstreifen abfährt, braucht bis Kızılağaç oft eine Stunde länger. TORVIAN fährt direkt — Transfer Antalya Flughafen zum Festpreis, Flugverfolgung, 24/7 ohne Nachtzuschlag.',
  description_pl = 'Kızılağaç leży 80 km od lotniska Antalya (AYT), około 1 godziny 10 minut prywatnym transferem — to najdalszy punkt pasa hotelowego Side, zanim wybrzeże skręca w stronę Alanyi. Jest spokojniejsze niż samo Side: duże hotele all inclusive cofnięte od długiej plaży, w pobliżu sosnowy las i laguna Titreyengöl, a kilka minut w głąb lądu miasto Manavgat. Właśnie ta większa odległość sprawia, że prywatny transfer się tu opłaca: autobus zbiorowy objeżdżający cały pas Side potrafi dojechać do Kızılağaç godzinę później. TORVIAN jedzie bezpośrednio: stała cena za pojazd, powitanie z tabliczką, monitoring lotu, 24/7 bez dopłaty nocnej.',
  description_ru = 'Кызылагач находится в 80 км от аэропорта Анталии (AYT), около 1 часа 10 минут на частном трансфере — это самая дальняя точка отельного пояса Сиде перед тем, как побережье поворачивает к Алании. Здесь спокойнее, чем в самом Сиде: крупные отели «всё включено» стоят чуть в стороне от длинного пляжа, рядом сосновый лес и лагуна Титреенгёль, а в нескольких минутах вглубь — город Манавгат. Именно из-за расстояния частный трансфер здесь особенно оправдан: групповой автобус, объезжающий всю полосу Сиде, добирается до Кызылагача на час позже. TORVIAN везёт напрямую: фиксированная цена, встреча с табличкой, отслеживание рейса, круглосуточно.',
  description_nl = 'Kızılağaç ligt 80 km van de luchthaven Antalya (AYT), ongeveer 1 uur 10 minuten met een privétransfer — het verste punt van de hotelstrook van Side voordat de kust naar Alanya afbuigt. Het is rustiger dan Side zelf: grote all-inclusive hotels iets terug van een lang strand, met het dennenbos en de lagune van Titreyengöl vlakbij en de stad Manavgat een paar minuten landinwaarts. Juist die extra afstand maakt een privétransfer hier de moeite waard: een gedeelde bus die de hele strook van Side afgaat, arriveert vaak een uur later. TORVIAN rijdt rechtstreeks: Antalya Airport transfer met vaste prijs per voertuig, ontvangst met naambord, vluchtmonitoring, 24/7 zonder nachttoeslag.'
WHERE slug = 'kizilagac';


-- ===== ŞEHİRİÇİ (Antalya city centre) — 12 km, 20 min =====
-- Different buyer from the resort regions: city hotels, business travellers,
-- cruise and short-stay guests rather than all-inclusive package tourists.
UPDATE regions SET
  description_en = 'Antalya city centre is just 12 km from Antalya Airport (AYT) — around 20 minutes by private transfer, the shortest ride we operate after Kundu-Lara. This covers Kaleiçi, the walled old town with its Roman harbour and Hadrian''s Gate, plus the Konyaaltı and Lara beach districts and the business hotels around the city. Guests here are typically city-break travellers, business visitors and cruise passengers rather than package tourists, and often arrive on late or early flights. Kaleiçi''s narrow lanes are partly closed to traffic; your driver stops at the nearest permitted point and helps with luggage. TORVIAN offers a private Antalya airport transfer with a fixed price per vehicle, name-board welcome and 24/7 service.',
  description_tr = 'Antalya şehir merkezi, Antalya Havalimanı''na (AYT) yalnızca 12 km — özel transferle yaklaşık 20 dakika; Kundu-Lara''dan sonra en kısa güzergâhımız. Bu bölge, Roma limanı ve Hadrian Kapısı ile surlarla çevrili Kaleiçi''ni, Konyaaltı ve Lara plaj semtlerini ve şehirdeki iş otellerini kapsar. Buraya gelenler genelde paket tatilci değil; şehir molası verenler, iş seyahatindekiler ve kruvaziyer yolcularıdır ve çoğu zaman geç ya da erken saatli uçuşlarla iner. Kaleiçi''nin dar sokakları kısmen trafiğe kapalıdır; şoförünüz en yakın izinli noktada durur ve bagajınızla yardım eder. TORVIAN: araç başına sabit fiyat, isim tabelasıyla karşılama, 7/24 hizmet.',
  description_de = 'Das Stadtzentrum von Antalya liegt nur 12 km vom Flughafen Antalya (AYT) entfernt — etwa 20 Minuten mit dem Privattransfer und nach Kundu-Lara unsere kürzeste Strecke. Dazu gehören Kaleiçi, die von einer Mauer umschlossene Altstadt mit römischem Hafen und Hadrianstor, die Strandviertel Konyaaltı und Lara sowie die Businesshotels der Stadt. Die Gäste hier sind eher Städtereisende, Geschäftsreisende und Kreuzfahrtpassagiere als Pauschaltouristen und landen häufig spät abends oder früh morgens. Die engen Gassen von Kaleiçi sind teilweise gesperrt; Ihr Fahrer hält am nächstgelegenen erlaubten Punkt und hilft mit dem Gepäck. TORVIAN: Transfer Antalya Flughafen zum Festpreis, Namensschild, 24/7.',
  description_pl = 'Centrum Antalyi leży zaledwie 12 km od lotniska Antalya (AYT) — około 20 minut prywatnym transferem, po Kundu-Lara nasza najkrótsza trasa. Obejmuje Kaleiçi, otoczone murami stare miasto z rzymskim portem i Bramą Hadriana, dzielnice plażowe Konyaaltı i Lara oraz hotele biznesowe w mieście. Goście to zwykle podróżni na city break, osoby w podróży służbowej i pasażerowie rejsów, a nie turyści pakietowi, i często przylatują późnym wieczorem lub wczesnym rankiem. Wąskie uliczki Kaleiçi są częściowo zamknięte dla ruchu; kierowca zatrzyma się w najbliższym dozwolonym miejscu i pomoże z bagażem. TORVIAN: stała cena za pojazd, powitanie z tabliczką, 24/7.',
  description_ru = 'Центр Анталии находится всего в 12 км от аэропорта (AYT) — около 20 минут на частном трансфере, наш самый короткий маршрут после Кунду-Лары. Сюда входят Калеичи, обнесённый стеной старый город с римской гаванью и воротами Адриана, пляжные районы Коньяалты и Лара, а также городские бизнес-отели. Гости здесь — чаще всего путешественники на короткий городской отдых, деловые визитёры и пассажиры круизов, а не пакетные туристы, и прилетают они нередко поздним вечером или ранним утром. Узкие улицы Калеичи частично закрыты для машин: водитель остановится в ближайшей разрешённой точке и поможет с багажом. TORVIAN: фиксированная цена за автомобиль, встреча с табличкой, круглосуточно.',
  description_nl = 'Het centrum van Antalya ligt op slechts 12 km van de luchthaven Antalya (AYT) — ongeveer 20 minuten met een privétransfer, na Kundu-Lara onze kortste rit. Hieronder vallen Kaleiçi, de ommuurde oude stad met Romeinse haven en de Hadrianuspoort, de strandwijken Konyaaltı en Lara, en de zakenhotels in de stad. De gasten hier zijn eerder citytrippers, zakelijke reizigers en cruisepassagiers dan pakketreizigers, en landen vaak laat op de avond of vroeg in de ochtend. De smalle straten van Kaleiçi zijn deels autovrij; uw chauffeur stopt op het dichtstbijzijnde toegestane punt en helpt met de bagage. TORVIAN: Antalya Airport transfer met vaste prijs per voertuig, naambord, 24/7.'
WHERE slug = 'sehirici';


-- Coverage check:
-- SELECT slug,
--        (description_en IS NOT NULL) AS en, (description_tr IS NOT NULL) AS tr,
--        (description_de IS NOT NULL) AS de, (description_pl IS NOT NULL) AS pl,
--        (description_ru IS NOT NULL) AS ru, (description_nl IS NOT NULL) AS nl
--   FROM regions WHERE slug IN ('kadriye','bogazkent','evrenseki','kizilagac','sehirici');
