-- 045: Unique region copy — Kemer corridor, all 6 languages
--
-- Third batch of the programme (see 043, 044). A region page is ~90% shared
-- template from src/messages/*.json; `description_<locale>` is the only block
-- that distinguishes it. Regions still on the 120-character seed text read as
-- near-duplicates and Google indexes almost none of them.
--
-- For de/pl/ru/nl these columns also control indexability: the region page
-- marks itself noindex unless description_<locale> or meta_title_<locale> is
-- filled (getTranslatedLocales in src/app/[locale]/[region]/page.tsx, mirrored
-- by src/app/sitemap.ts).
--
-- DISTANCES — supabase/seed.sql, the live regions data:
--   beldibi 40 km / 35 min · goynuk 50 km / 40 min · kiris 60 km / 55 min
--   camyuva 65 km / 55 min · tekirova 70 km / 60 min · adrasan 95 km / 90 min
--
-- Russian gets extra care here: Search Console shows the site's single
-- largest non-English cluster is Russian queries about the Kemer route
-- ("расстояние от аэропорта анталии до кемера", "анталья аэропорт кемер
-- расстояние", "сколько ехать от анталии до кемера") — over 250 impressions
-- across variants, all currently converting at roughly zero.
--
-- German keyword: Trends DE puts "hotel transfer antalya" at 69 and
-- "transfer antalya flughafen" at 100; both appear in the German copy.
--
-- Safe to re-run.


-- ===== BELDİBİ — 40 km, 35 min =====
UPDATE regions SET
  description_en = 'Beldibi is the first resort you reach on the Kemer road, 40 km from Antalya Airport (AYT) and about 35 minutes away by private transfer. It sits where the Taurus mountains drop straight into the sea, with pebble beaches backed by pine forest and a string of family hotels along the shore. Being the closest point of the Kemer strip, it is also the quickest to reach after a late landing, and close enough to Antalya city for an easy day trip to Kaleiçi. TORVIAN provides a private airport transfer from Antalya to any hotel in Beldibi: fixed price per vehicle, meet and greet with a name board, live flight tracking, and 24/7 service with no night surcharge.',
  description_tr = 'Beldibi, Kemer yolundaki ilk tatil bölgesidir; Antalya Havalimanı''na (AYT) 40 km uzaklıkta ve özel transferle yaklaşık 35 dakika mesafededir. Toros Dağları''nın denize dik indiği noktada yer alır; çam ormanının arkasındaki çakıl plajlar ve sahil boyunca uzanan aile otelleriyle bilinir. Kemer şeridinin havalimanına en yakın noktası olduğu için geç saatli inişlerde en hızlı ulaşılan yerdir ve Kaleiçi''ne günübirlik gitmek için Antalya''ya yeterince yakındır. TORVIAN, Antalya Havalimanı''ndan Beldibi''ndeki her otele özel transfer sunar: araç başına sabit fiyat, isim tabelasıyla karşılama, canlı uçuş takibi, 7/24 ve gece zammı yok.',
  description_de = 'Beldibi ist der erste Ferienort an der Strasse nach Kemer, 40 km vom Flughafen Antalya (AYT) entfernt und in etwa 35 Minuten mit dem Privattransfer erreichbar. Hier fällt das Taurusgebirge direkt ins Meer ab: Kieselstrände vor Kiefernwald und eine Reihe von Familienhotels entlang der Küste. Als flughafennächster Punkt des Küstenstreifens von Kemer ist Beldibi nach einer späten Landung am schnellsten erreicht und liegt nah genug an Antalya für einen Tagesausflug in die Altstadt Kaleiçi. TORVIAN bietet Hotel Transfer Antalya nach Beldibi: Festpreis pro Fahrzeug, Abholung mit Namensschild, Flugverfolgung, 24/7 ohne Nachtzuschlag.',
  description_pl = 'Beldibi to pierwszy kurort na drodze do Kemer, 40 km od lotniska Antalya (AYT) i około 35 minut prywatnym transferem. Leży tam, gdzie góry Taurus opadają wprost do morza: kamieniste plaże osłonięte sosnowym lasem i szereg hoteli rodzinnych wzdłuż brzegu. Jako najbliższy lotniska punkt pasa Kemer jest najszybciej osiągalny po późnym lądowaniu, a jednocześnie dość blisko Antalyi, by wybrać się na jednodniową wycieczkę do Kaleiçi. TORVIAN oferuje prywatny transfer z lotniska Antalya do każdego hotelu w Beldibi: stała cena za pojazd, powitanie z tabliczką, monitoring lotu, 24/7 bez dopłaty nocnej.',
  description_ru = 'Бельдиби — первый курорт на дороге в Кемер, в 40 км от аэропорта Анталии (AYT), около 35 минут на частном трансфере. Здесь Таврские горы обрываются прямо к морю: галечные пляжи, сосновый лес за ними и вереница семейных отелей вдоль берега. Это ближайшая к аэропорту точка кемерского побережья, поэтому после позднего рейса сюда добираются быстрее всего, а до Анталии достаточно близко, чтобы съездить на день в Калеичи. TORVIAN выполняет частный трансфер из аэропорта Анталии в любой отель Бельдиби: фиксированная цена за автомобиль, встреча с табличкой, отслеживание рейса, круглосуточно и без ночной наценки.',
  description_nl = 'Beldibi is de eerste badplaats die u tegenkomt op de weg naar Kemer, 40 km van de luchthaven Antalya (AYT) en ongeveer 35 minuten met een privétransfer. Hier duikt het Taurusgebergte recht de zee in: kiezelstranden met dennenbos erachter en een rij gezinshotels langs de kust. Als dichtstbijzijnde punt van de Kemer-strook bent u er na een late landing het snelst, en Antalya ligt dicht genoeg voor een dagje Kaleiçi. TORVIAN verzorgt een Antalya Airport transfer naar elk hotel in Beldibi: vaste prijs per voertuig, ontvangst met naambord, vluchtmonitoring, 24/7 zonder nachttoeslag.'
WHERE slug = 'beldibi';


-- ===== GÖYNÜK — 50 km, 40 min =====
UPDATE regions SET
  description_en = 'Göynük lies 50 km from Antalya Airport (AYT), roughly 40 minutes by private transfer, midway between Beldibi and Kemer. It is best known for Göynük Canyon, a narrow gorge a short drive inland where the river runs between sheer rock walls — one of the most popular half-day trips on this coast. The village itself has a long pebble beach, a quiet promenade and mid-sized resort hotels rather than the high-rise developments further east. Guests here often combine the beach with canyoning, so we can accommodate bulky gear on request. TORVIAN drives door to door from the airport: fixed price per vehicle, name-board welcome, flight tracking, 24/7.',
  description_tr = 'Göynük, Antalya Havalimanı''na (AYT) 50 km uzaklıkta, özel transferle yaklaşık 40 dakika mesafede, Beldibi ile Kemer arasında yer alır. En çok Göynük Kanyonu ile bilinir: kısa bir iç kesim sürüşüyle ulaşılan, derenin dik kaya duvarları arasından aktığı dar bir vadi — bu sahilin en popüler yarım günlük gezilerinden biri. Beldenin kendisinde uzun bir çakıl plaj, sakin bir sahil yolu ve doğudaki yüksek bloklar yerine orta ölçekli tatil otelleri vardır. Buraya gelenler çoğu zaman plajı kanyon yürüyüşüyle birleştirir; hacimli ekipman için talep üzerine yer ayırırız. TORVIAN havalimanından kapıya kadar götürür: sabit fiyat, karşılama, uçuş takibi, 7/24.',
  description_de = 'Göynük liegt 50 km vom Flughafen Antalya (AYT) entfernt, etwa 40 Minuten mit dem Privattransfer, auf halbem Weg zwischen Beldibi und Kemer. Bekannt ist der Ort vor allem für den Göynük-Canyon, eine enge Schlucht wenige Fahrminuten landeinwärts, in der der Fluss zwischen steilen Felswänden verläuft — einer der beliebtesten Halbtagesausflüge dieser Küste. Der Ort selbst hat einen langen Kiesstrand, eine ruhige Promenade und mittelgrosse Resorthotels statt der Hochhäuser weiter östlich. Viele Gäste verbinden Strand und Canyoning; sperrige Ausrüstung planen wir auf Anfrage ein. TORVIAN: Transfer Antalya Flughafen bis vor die Tür, Festpreis, Flugverfolgung, 24/7.',
  description_pl = 'Göynük leży 50 km od lotniska Antalya (AYT), około 40 minut prywatnym transferem, w połowie drogi między Beldibi a Kemer. Najbardziej znany jest z kanionu Göynük — wąskiego wąwozu kilka minut w głąb lądu, gdzie rzeka płynie między pionowymi ścianami skalnymi; to jedna z najpopularniejszych półdniowych wycieczek na tym wybrzeżu. Sama miejscowość ma długą kamienistą plażę, spokojną promenadę i średniej wielkości hotele zamiast wieżowców dalej na wschód. Goście często łączą plażowanie z canyoningiem, a na życzenie zaplanujemy miejsce na obszerny sprzęt. TORVIAN dowozi pod drzwi: stała cena, monitoring lotu, 24/7.',
  description_ru = 'Гёйнюк находится в 50 км от аэропорта Анталии (AYT), около 40 минут на частном трансфере, на полпути между Бельдиби и Кемером. Известен прежде всего каньоном Гёйнюк — узким ущельем в нескольких минутах езды вглубь берега, где река течёт между отвесными скалами; это одна из самых популярных экскурсий на полдня на этом побережье. В самом посёлке длинный галечный пляж, спокойная набережная и отели среднего размера вместо высоток восточнее. Гости часто совмещают пляж с каньонингом — объёмное снаряжение мы учитываем заранее по запросу. TORVIAN везёт от аэропорта до дверей отеля: фиксированная цена, встреча с табличкой, отслеживание рейса, круглосуточно.',
  description_nl = 'Göynük ligt 50 km van de luchthaven Antalya (AYT), ongeveer 40 minuten met een privétransfer, halverwege Beldibi en Kemer. Het dorp is vooral bekend om de Göynük-kloof, een smalle bergkloof enkele minuten landinwaarts waar de rivier tussen steile rotswanden doorloopt — een van de populairste halvedagtochten van deze kust. Het dorp zelf heeft een lang kiezelstrand, een rustige boulevard en middelgrote resorthotels in plaats van de hoogbouw verderop. Gasten combineren het strand vaak met canyoning; ruimte voor omvangrijke uitrusting regelen wij op aanvraag. TORVIAN rijdt van de luchthaven tot aan de deur: vaste prijs, vluchtmonitoring, 24/7.'
WHERE slug = 'goynuk';


-- ===== KİRİŞ — 60 km, 55 min =====
UPDATE regions SET
  description_en = 'Kiriş is a small resort just south of Kemer centre, 60 km from Antalya Airport (AYT) and about 55 minutes by private transfer. Pine forest comes right down to the shore here, and the hotels — mostly mid-size, many with their own stretch of pebble beach — are spread through the trees rather than lined up along a promenade. It is quieter than Kemer itself while still being a ten-minute walk or a short taxi ride from its marina, bars and market. Because the hotels sit back among the pines, entrances are easy to miss after dark, so we ask for the exact hotel name when you book. TORVIAN: private airport transfer, fixed price per vehicle, flight tracking, 24/7.',
  description_tr = 'Kiriş, Kemer merkezinin hemen güneyinde küçük bir tatil beldesidir; Antalya Havalimanı''na (AYT) 60 km uzaklıkta ve özel transferle yaklaşık 55 dakika mesafededir. Burada çam ormanı doğrudan sahile iner; oteller — çoğu orta ölçekli ve birçoğu kendi çakıl plajına sahip — bir sahil yolu boyunca sıralanmak yerine ağaçların arasına dağılmıştır. Kemer''in kendisinden daha sakindir, yine de marinaya, barlara ve pazara on dakikalık yürüyüş ya da kısa bir taksi mesafesindedir. Oteller çamların arasında geride kaldığı için girişler hava karardıktan sonra kolayca kaçırılır; bu yüzden rezervasyonda tam otel adını isteriz. TORVIAN: özel transfer, sabit fiyat, uçuş takibi, 7/24.',
  description_de = 'Kiriş ist ein kleiner Ferienort südlich des Zentrums von Kemer, 60 km vom Flughafen Antalya (AYT) entfernt und in etwa 55 Minuten mit dem Privattransfer erreichbar. Der Kiefernwald reicht hier bis ans Ufer, und die Hotels — meist mittelgross, viele mit eigenem Kiesstrandabschnitt — verteilen sich zwischen den Bäumen statt sich an einer Promenade aufzureihen. Ruhiger als Kemer selbst, aber nur zehn Gehminuten oder eine kurze Taxifahrt von Marina, Bars und Markt entfernt. Da die Hotels zwischen den Pinien zurückliegen, sind die Einfahrten nach Einbruch der Dunkelheit leicht zu übersehen — wir erfragen daher den genauen Hotelnamen. TORVIAN: Privattransfer Antalya Flughafen, Festpreis, 24/7.',
  description_pl = 'Kiriş to niewielki kurort tuż na południe od centrum Kemer, 60 km od lotniska Antalya (AYT) i około 55 minut prywatnym transferem. Sosnowy las schodzi tu wprost do brzegu, a hotele — przeważnie średniej wielkości, wiele z własnym odcinkiem kamienistej plaży — rozproszone są między drzewami zamiast ustawione wzdłuż promenady. Jest spokojniej niż w samym Kemer, a mimo to marina, bary i targ są o dziesięć minut spacerem lub krótki kurs taksówką. Ponieważ hotele stoją w głębi sosnowego lasu, wjazdy łatwo przeoczyć po zmroku, dlatego prosimy o dokładną nazwę hotelu. TORVIAN: prywatny transfer z lotniska, stała cena, monitoring lotu, 24/7.',
  description_ru = 'Кириш — небольшой курорт сразу к югу от центра Кемера, в 60 км от аэропорта Анталии (AYT), около 55 минут на частном трансфере. Сосновый лес здесь подходит к самой воде, а отели — в основном среднего размера, у многих собственный участок галечного пляжа — разбросаны между деревьями, а не выстроены вдоль набережной. Тише, чем в самом Кемере, но до марины, баров и рынка десять минут пешком или короткая поездка на такси. Отели стоят в глубине сосняка, и въезды легко пропустить в темноте, поэтому мы просим точное название отеля при бронировании. TORVIAN: частный трансфер из аэропорта, фиксированная цена, отслеживание рейса, круглосуточно.',
  description_nl = 'Kiriş is een kleine badplaats net ten zuiden van het centrum van Kemer, 60 km van de luchthaven Antalya (AYT) en ongeveer 55 minuten met een privétransfer. Het dennenbos loopt hier door tot aan de kustlijn, en de hotels — meestal middelgroot, veel met een eigen stuk kiezelstrand — liggen verspreid tussen de bomen in plaats van op een rij langs een boulevard. Rustiger dan Kemer zelf, maar de jachthaven, bars en markt liggen op tien minuten lopen of een korte taxirit. Doordat de hotels tussen de pijnbomen terugliggen, zijn de opritten na donker makkelijk te missen; wij vragen daarom de exacte hotelnaam. TORVIAN: Antalya Airport transfer, vaste prijs, vluchtmonitoring, 24/7.'
WHERE slug = 'kiris';


-- ===== ÇAMYUVA — 65 km, 55 min =====
UPDATE regions SET
  description_en = 'Çamyuva sits 65 km from Antalya Airport (AYT), about 55 minutes by private transfer, south of Kiriş along the Kemer coast. Its name means "pine nest", which describes it well: the resorts here are set among dense pine woods that run down to a quiet pebble beach, with the Taurus ridge rising directly behind. There is no nightlife strip and no through traffic — guests come for the calm, and for the walking and mountain-biking trails that start at the edge of the village. Transfers here take slightly longer than the distance suggests because the last stretch is a winding coastal road. TORVIAN: private transfer from Antalya Airport, fixed price, meet and greet, flight tracking, 24/7.',
  description_tr = 'Çamyuva, Antalya Havalimanı''na (AYT) 65 km uzaklıkta, özel transferle yaklaşık 55 dakika mesafede, Kemer sahilinde Kiriş''in güneyinde yer alır. Adı yerini iyi anlatır: buradaki tesisler, sakin bir çakıl plaja inen sık çam ormanının içine kurulmuştur; hemen arkalarında Toros sırtı yükselir. Gece hayatı caddesi ve transit trafik yoktur — konuklar sükûnet için, bir de köyün kenarından başlayan yürüyüş ve dağ bisikleti parkurları için gelir. Son bölüm virajlı bir sahil yolu olduğundan transfer, mesafenin düşündürdüğünden biraz uzun sürer. TORVIAN: Antalya Havalimanı''ndan özel transfer, sabit fiyat, karşılama, uçuş takibi, 7/24.',
  description_de = 'Çamyuva liegt 65 km vom Flughafen Antalya (AYT) entfernt, etwa 55 Minuten mit dem Privattransfer, südlich von Kiriş an der Küste von Kemer. Der Name bedeutet "Pinienhorst" und trifft es gut: Die Anlagen liegen in dichtem Kiefernwald, der bis zu einem ruhigen Kiesstrand hinabreicht, dahinter steigt der Taurus unmittelbar an. Es gibt keine Partymeile und keinen Durchgangsverkehr — Gäste kommen wegen der Ruhe und wegen der Wander- und Mountainbike-Wege am Ortsrand. Der Transfer dauert etwas länger, als die Entfernung vermuten lässt, weil das letzte Stück eine kurvige Küstenstrasse ist. TORVIAN: Hotel Transfer Antalya zum Festpreis, Namensschild, Flugverfolgung, 24/7.',
  description_pl = 'Çamyuva leży 65 km od lotniska Antalya (AYT), około 55 minut prywatnym transferem, na południe od Kiriş wzdłuż wybrzeża Kemer. Nazwa oznacza "sosnowe gniazdo" i dobrze oddaje charakter miejsca: ośrodki stoją w gęstym sosnowym lesie schodzącym do spokojnej kamienistej plaży, a tuż za nimi wznosi się grzbiet Taurusu. Nie ma tu deptaka z klubami ani ruchu tranzytowego — goście przyjeżdżają dla ciszy oraz szlaków pieszych i rowerowych zaczynających się na skraju wsi. Transfer trwa nieco dłużej, niż sugeruje odległość, bo ostatni odcinek to kręta droga nadmorska. TORVIAN: prywatny transfer z lotniska Antalya, stała cena, monitoring lotu, 24/7.',
  description_ru = 'Чамьюва расположена в 65 км от аэропорта Анталии (AYT), около 55 минут на частном трансфере, южнее Кириша по кемерскому побережью. Название переводится как «сосновое гнездо», и это точно описывает место: отели стоят в густом сосновом лесу, спускающемся к тихому галечному пляжу, а сразу за ними поднимается хребет Тавра. Здесь нет улицы баров и нет транзитного движения — сюда едут за тишиной, а также ради пеших и велосипедных маршрутов, начинающихся у окраины посёлка. Трансфер занимает чуть больше времени, чем можно предположить по километражу: последний участок — извилистая прибрежная дорога. TORVIAN: частный трансфер, фиксированная цена, встреча с табличкой, круглосуточно.',
  description_nl = 'Çamyuva ligt 65 km van de luchthaven Antalya (AYT), ongeveer 55 minuten met een privétransfer, ten zuiden van Kiriş langs de kust van Kemer. De naam betekent "dennennest" en dat dekt de lading: de resorts staan in dicht dennenbos dat afloopt naar een rustig kiezelstrand, met de bergkam van de Taurus er direct achter. Er is geen uitgaansstraat en geen doorgaand verkeer — gasten komen voor de rust en voor de wandel- en mountainbikeroutes die aan de rand van het dorp beginnen. De transfer duurt iets langer dan de afstand doet vermoeden, want het laatste stuk is een bochtige kustweg. TORVIAN: privétransfer vanaf de luchthaven, vaste prijs, vluchtmonitoring, 24/7.'
WHERE slug = 'camyuva';


-- ===== TEKİROVA — 70 km, 1 h =====
UPDATE regions SET
  description_en = 'Tekirova is the southernmost resort of the Kemer strip, 70 km from Antalya Airport (AYT) and about an hour away by private transfer. Its main draw is location: the ruins of ancient Phaselis, with three natural harbours and a Roman aqueduct running down to the water, are a few minutes up the road, and the Olympos cable car to the 2,365 m summit of Tahtalı starts nearby. The beach is clean pebble, the water is famously clear, and the hotels are large all-inclusive resorts set in landscaped pine grounds. The winding coastal approach makes a private car noticeably more comfortable than a shared bus here. TORVIAN: fixed price per vehicle, name-board welcome, flight tracking, 24/7.',
  description_tr = 'Tekirova, Kemer şeridinin en güneydeki tatil bölgesidir; Antalya Havalimanı''na (AYT) 70 km uzaklıkta ve özel transferle yaklaşık bir saat mesafededir. Asıl cazibesi konumudur: üç doğal limanı ve suya inen Roma su kemeriyle antik Faselis kalıntıları yolun birkaç dakika yukarısındadır; Tahtalı''nın 2.365 metrelik zirvesine çıkan Olympos teleferiği de yakındadır. Plaj temiz çakıldır, denizi berraklığıyla ünlüdür ve oteller peyzajlı çam arazilerine kurulmuş büyük her şey dahil tesislerdir. Virajlı sahil yaklaşımı, burada özel aracı grup otobüsüne göre belirgin biçimde daha konforlu kılar. TORVIAN: araç başına sabit fiyat, isim tabelasıyla karşılama, uçuş takibi, 7/24.',
  description_de = 'Tekirova ist der südlichste Ferienort des Küstenstreifens von Kemer, 70 km vom Flughafen Antalya (AYT) entfernt und in etwa einer Stunde mit dem Privattransfer erreichbar. Sein Reiz ist die Lage: Die Ruinen des antiken Phaselis mit drei Naturhäfen und einem römischen Aquädukt bis ans Wasser liegen wenige Fahrminuten entfernt, und die Olympos-Seilbahn auf den 2.365 m hohen Tahtalı startet in der Nähe. Der Strand ist sauberer Kies, das Wasser bekannt klar, die Hotels sind grosse All-inclusive-Anlagen in gepflegten Pinienparks. Die kurvige Küstenanfahrt macht den Privatwagen hier spürbar bequemer als einen Sammelbus. TORVIAN: Transfer Antalya Flughafen, Festpreis, Flugverfolgung, 24/7.',
  description_pl = 'Tekirova to najdalej na południe wysunięty kurort pasa Kemer, 70 km od lotniska Antalya (AYT) i około godziny prywatnym transferem. Jego atutem jest położenie: ruiny starożytnego Phaselis z trzema naturalnymi portami i rzymskim akweduktem schodzącym do wody leżą kilka minut drogi dalej, a kolejka linowa Olympos na szczyt Tahtalı (2365 m) startuje w pobliżu. Plaża jest czysta i kamienista, woda słynie z przejrzystości, a hotele to duże ośrodki all inclusive w zadbanych sosnowych parkach. Kręty dojazd nadmorski sprawia, że prywatny samochód jest tu wyraźnie wygodniejszy niż autobus zbiorowy. TORVIAN: stała cena za pojazd, powitanie z tabliczką, monitoring lotu, 24/7.',
  description_ru = 'Текирова — самый южный курорт кемерского побережья, в 70 км от аэропорта Анталии (AYT), около часа на частном трансфере. Главное её преимущество — расположение: руины античного Фаселиса с тремя естественными гаванями и римским акведуком, спускающимся к воде, находятся в нескольких минутах езды, а рядом начинается канатная дорога Олимпос на вершину Тахталы высотой 2365 м. Пляж — чистая галька, вода славится прозрачностью, отели — крупные комплексы «всё включено» в ухоженных сосновых парках. Извилистый подъезд по побережью делает частный автомобиль здесь заметно комфортнее группового автобуса. TORVIAN: фиксированная цена за машину, встреча с табличкой, отслеживание рейса, круглосуточно.',
  description_nl = 'Tekirova is de zuidelijkste badplaats van de Kemer-strook, 70 km van de luchthaven Antalya (AYT) en ongeveer een uur met een privétransfer. De ligging is de grote troef: de ruïnes van het antieke Phaselis, met drie natuurlijke havens en een Romeins aquaduct dat tot aan het water loopt, liggen enkele minuten verderop, en de Olympos-kabelbaan naar de 2.365 meter hoge top van de Tahtalı vertrekt vlakbij. Het strand is schoon kiezelstrand, het water staat bekend om zijn helderheid, en de hotels zijn grote all-inclusive resorts in aangelegde dennenparken. De bochtige kustweg maakt een privéauto hier merkbaar comfortabeler dan een gedeelde bus. TORVIAN: vaste prijs, naambord, vluchtmonitoring, 24/7.'
WHERE slug = 'tekirova';


-- ===== ADRASAN — 95 km, 1 h 30 min =====
UPDATE regions SET
  description_en = 'Adrasan is a small bay 95 km from Antalya Airport (AYT), about an hour and a half away by private transfer. It lies beyond the Kemer resorts, reached by a mountain road that leaves the coast and climbs over a pass before dropping into the valley — which is precisely why it has stayed quiet. The bay is a curve of sand and pebble with family-run pensions and small hotels rather than large resorts, and the Lycian Way passes above it, with Olympos and the Chimaera flames a short drive north. There is no shuttle service worth the name out here, so a private transfer is effectively the only direct option. TORVIAN: fixed price per vehicle, flight tracking, 24/7, no night surcharge.',
  description_tr = 'Adrasan, Antalya Havalimanı''na (AYT) 95 km uzaklıkta, özel transferle yaklaşık bir buçuk saat mesafede küçük bir koydur. Kemer tesislerinin ötesinde kalır; sahilden ayrılıp bir geçidi aşan ve ardından vadiye inen dağ yoluyla ulaşılır — sakinliğini korumasının sebebi tam olarak budur. Koy, büyük tesisler yerine aile işletmesi pansiyonlar ve küçük otellerin bulunduğu bir kum-çakıl yayıdır; Likya Yolu hemen üzerinden geçer, Olympos ve Yanartaş ise kısa bir kuzey sürüşü mesafesindedir. Burada adı anılacak bir servis hattı yoktur; bu yüzden özel transfer pratikte tek doğrudan seçenektir. TORVIAN: araç başına sabit fiyat, uçuş takibi, 7/24, gece zammı yok.',
  description_de = 'Adrasan ist eine kleine Bucht 95 km vom Flughafen Antalya (AYT) entfernt, etwa anderthalb Stunden mit dem Privattransfer. Sie liegt hinter den Ferienorten von Kemer und wird über eine Bergstrasse erreicht, die von der Küste abzweigt, einen Pass überquert und dann ins Tal abfällt — genau deshalb ist es hier ruhig geblieben. Die Bucht ist ein Bogen aus Sand und Kies mit familiengeführten Pensionen und kleinen Hotels statt grosser Anlagen; der Lykische Weg verläuft oberhalb, Olympos und die Chimaera-Flammen sind eine kurze Fahrt nach Norden. Einen nennenswerten Shuttle gibt es hier nicht — der Privattransfer ist praktisch die einzige Direktverbindung. TORVIAN: Festpreis, Flugverfolgung, 24/7.',
  description_pl = 'Adrasan to niewielka zatoka 95 km od lotniska Antalya (AYT), około półtorej godziny prywatnym transferem. Leży za kurortami Kemer, a dojeżdża się do niej górską drogą, która odbija od wybrzeża, pokonuje przełęcz i opada do doliny — właśnie dlatego pozostała cicha. Zatokę tworzy łuk piasku i kamieni z rodzinnymi pensjonatami i małymi hotelami zamiast dużych ośrodków; powyżej biegnie Szlak Licyjski, a Olympos i płomienie Chimery są krótką jazdą na północ. Nie ma tu żadnego sensownego transferu zbiorowego, więc prywatny przejazd jest praktycznie jedyną bezpośrednią opcją. TORVIAN: stała cena za pojazd, monitoring lotu, 24/7, bez dopłaty nocnej.',
  description_ru = 'Адрасан — небольшая бухта в 95 км от аэропорта Анталии (AYT), около полутора часов на частном трансфере. Она лежит за курортами Кемера, и добираются до неё по горной дороге, которая уходит от побережья, перебирается через перевал и спускается в долину — именно поэтому здесь до сих пор тихо. Бухта представляет собой дугу песка и гальки с семейными пансионами и небольшими отелями вместо крупных комплексов; выше проходит Ликийская тропа, а Олимпос и огни Химеры — в короткой поездке к северу. Никакого сколько-нибудь удобного группового транспорта сюда нет, поэтому частный трансфер фактически единственный прямой вариант. TORVIAN: фиксированная цена, отслеживание рейса, круглосуточно.',
  description_nl = 'Adrasan is een kleine baai op 95 km van de luchthaven Antalya (AYT), ongeveer anderhalf uur met een privétransfer. Het ligt voorbij de badplaatsen van Kemer en is bereikbaar via een bergweg die de kust verlaat, over een pas klimt en daarna het dal in duikt — precies daarom is het er rustig gebleven. De baai is een boog van zand en kiezels met familiepensions en kleine hotels in plaats van grote resorts; de Lycische Weg loopt erboven langs en Olympos met de vlammen van de Chimaera ligt een korte rit noordwaarts. Een noemenswaardige pendeldienst is er niet, dus een privétransfer is hier praktisch de enige directe optie. TORVIAN: vaste prijs, vluchtmonitoring, 24/7.'
WHERE slug = 'adrasan';


-- Coverage check:
-- SELECT slug,
--        (description_en IS NOT NULL) AS en, (description_tr IS NOT NULL) AS tr,
--        (description_de IS NOT NULL) AS de, (description_pl IS NOT NULL) AS pl,
--        (description_ru IS NOT NULL) AS ru, (description_nl IS NOT NULL) AS nl
--   FROM regions WHERE slug IN ('beldibi','goynuk','kiris','camyuva','tekirova','adrasan');
