-- 047: Unique region copy — Lycian coast + western long-haul
--
-- Fifth and final batch of the region programme (see 043, 044, 045, 046).
-- Covers the four far-west destinations still on the 120-char seed text:
--
--   kas       190 km / 3 h        Lycian coast, diving, boutique/bohemian
--   kalkan    210 km / 3 h 10 min hillside villas with pools, upscale couples
--   fethiye   220 km / 3 h 20 min large resort town, Ölüdeniz / paragliding
--   marmaris  300 km / 4 h 30 min Muğla, longest AYT route, marina / nightlife
--
-- Distances come from supabase/seed.sql — the live regions data. Migration
-- 010's DELETE left seed.sql as the single source of truth for km/min, so copy
-- that contradicts it shows up as a distance mismatch on the rendered page
-- (region cards read from the same row).
--
-- For de/pl/ru/nl these description_<locale> columns also control
-- indexability: the region page marks itself noindex unless
-- description_<locale> or meta_title_<locale> is filled
-- (getTranslatedLocales in src/app/[locale]/[region]/page.tsx, mirrored by
-- src/app/sitemap.ts).
--
-- Character of this batch differs from the Alanya strip: these are long,
-- 3–4.5 hour routes where the honest selling point is a single comfortable
-- door-to-door car versus multiple bus changes through Antalya otogar. Fethiye
-- and Marmaris are physically closer to Dalaman (DLM); the copy names that
-- openly, because pretending otherwise erodes trust — the value we sell is the
-- comfortable transfer for travellers whose itinerary actually lands at AYT.
-- The British market is strong for Fethiye/Marmaris, so English carries full
-- weight there rather than Russian.
--
-- Safe to re-run.


-- ===== KAŞ — 190 km, 3 h =====
UPDATE regions SET
  description_en = 'Kaş sits 190 km from Antalya Airport (AYT), about 3 hours by private transfer along the coastal D400. It is the quiet, upmarket end of the Lycian coast — a small fishing harbour, a Greek-influenced old town of bougainvillea-draped lanes, and boutique hotels rather than the big all-inclusive resorts further east. People come here to dive the clear water off the Kekova sunken city, to paraglide, and to eat well without the crowds. The trade-off is distance: reaching Kaş by public transport means a bus to Antalya otogar and a change onto a slow coastal service, easily five hours or more. A private transfer is one comfortable car straight to your hotel, with a rest stop on the way. TORVIAN: fixed price per vehicle, meet and greet, flight tracking, 24/7.',
  description_tr = 'Kaş, Antalya Havalimanı''na (AYT) 190 km uzaklıkta, sahil yolu D400 üzerinden özel transferle yaklaşık 3 saat mesafededir. Likya kıyısının sakin ve seçkin ucudur — küçük bir balıkçı limanı, begonvillerle örülü sokaklarıyla Rum mimarisi izleri taşıyan bir eski kent ve doğudaki büyük her şey dahil tesisler yerine butik oteller. Buraya Kekova batık kentinin berrak sularında dalış yapmak, yamaç paraşütü uçmak ve kalabalık olmadan güzel yemek için gelinir. Bedeli mesafedir: Kaş''a toplu taşımayla ulaşmak, Antalya otogarına bir otobüs ve ardından yavaş bir sahil hattına aktarma demektir; kolayca beş saati aşar. Özel transfer, yolda mola verilen, doğrudan otelinize giden tek konforlu araçtır. TORVIAN: araç başına sabit fiyat, isim tabelasıyla karşılama, uçuş takibi, 7/24.',
  description_de = 'Kaş liegt 190 km vom Flughafen Antalya (AYT) entfernt, etwa 3 Stunden mit dem Privattransfer über die Küstenstrasse D400. Es ist das ruhige, gehobene Ende der lykischen Küste — ein kleiner Fischerhafen, eine von Bougainvillea überwucherte Altstadt mit griechischem Einschlag und Boutiquehotels statt der grossen All-inclusive-Anlagen weiter östlich. Man kommt hierher, um im klaren Wasser der versunkenen Stadt Kekova zu tauchen, gleitzuschirmen und ohne Menschenmassen gut zu essen. Der Preis dafür ist die Entfernung: mit öffentlichen Verkehrsmitteln bedeutet Kaş einen Bus zum Busbahnhof Antalya und ein Umsteigen in eine langsame Küstenlinie, leicht fünf Stunden oder mehr. Ein Privattransfer ist ein bequemes Auto direkt zum Hotel, mit einer Pause unterwegs. TORVIAN: Hotel Transfer Antalya, Festpreis pro Fahrzeug, Namensschild, Flugverfolgung, 24/7.',
  description_pl = 'Kaş leży 190 km od lotniska Antalya (AYT), około 3 godzin prywatnym transferem nadmorską trasą D400. To spokojny, ekskluzywny kraniec wybrzeża licyjskiego — mały port rybacki, stare miasteczko o greckim charakterze z uliczkami tonącymi w bugenwillach i butikowe hotele zamiast wielkich ośrodków all inclusive dalej na wschód. Przyjeżdża się tu, by nurkować w przejrzystej wodzie przy zatopionym mieście Kekova, latać na paralotni i dobrze zjeść bez tłumów. Ceną jest odległość: dojazd komunikacją publiczną oznacza autobus na dworzec w Antalyi i przesiadkę na wolną linię nadmorską, łatwo pięć godzin lub więcej. Prywatny transfer to jeden wygodny samochód prosto pod hotel, z postojem po drodze. TORVIAN: stała cena za pojazd, powitanie z tabliczką, monitoring lotu, 24/7.',
  description_ru = 'Каш находится в 190 км от аэропорта Анталии (AYT), около 3 часов на частном трансфере по прибрежной дороге D400. Это тихий, статусный край Ликийского побережья — небольшая рыбацкая гавань, старый город с греческим характером и утопающими в бугенвиллее улочками, бутик-отели вместо крупных отелей «всё включено» восточнее. Сюда едут нырять в прозрачной воде у затонувшего города Кекова, летать на параплане и хорошо есть без толп. Плата за это — расстояние: на общественном транспорте Каш означает автобус до автовокзала Анталии и пересадку на медленный прибрежный рейс, легко пять часов и больше. Частный трансфер — один комфортный автомобиль прямо к отелю, с остановкой в пути. TORVIAN: фиксированная цена за автомобиль, встреча с табличкой, отслеживание рейса, круглосуточно.',
  description_nl = 'Kaş ligt 190 km van de luchthaven Antalya (AYT), ongeveer 3 uur met een privétransfer over de kustweg D400. Het is het rustige, chique einde van de Lycische kust — een kleine vissershaven, een oude stad met Griekse invloeden en met bougainville begroeide straatjes, en boetiekhotels in plaats van de grote all-inclusive resorts verderop oostwaarts. Men komt hier om te duiken in het heldere water bij de verzonken stad Kekova, om te paragliden en om goed te eten zonder de drukte. De prijs daarvoor is de afstand: met het openbaar vervoer betekent Kaş een bus naar het busstation van Antalya en een overstap op een trage kustlijn, al gauw vijf uur of meer. Een privétransfer is één comfortabele auto rechtstreeks naar uw hotel, met een pauze onderweg. TORVIAN: vaste prijs per voertuig, ontvangst met naambord, vluchtmonitoring, 24/7.'
WHERE slug = 'kas';


-- ===== KALKAN — 210 km, 3 h 10 min =====
UPDATE regions SET
  description_en = 'Kalkan lies 210 km from Antalya Airport (AYT), about 3 hours 10 minutes by private transfer, on the Lycian coast just west of Kaş. It is a town built into a steep hillside above Kalamar bay: whitewashed houses tumbling down to a small old harbour, and above them the villa district that defines Kalkan — hundreds of private villas with infinity pools looking out over the sea. There is no big sandy beach; swimming is from beach clubs and platforms, and the evenings belong to the rooftop restaurants the town is known for. It is a destination for couples, honeymooners and villa groups rather than package families. The steep lanes and scattered villa addresses make a private transfer with the exact address the sensible way to arrive. TORVIAN: fixed price per vehicle, meet and greet, flight tracking, 24/7.',
  description_tr = 'Kalkan, Antalya Havalimanı''na (AYT) 210 km uzaklıkta, özel transferle yaklaşık 3 saat 10 dakika mesafede, Likya kıyısında Kaş''ın hemen batısında yer alır. Kalamar koyunun üzerinde dik bir yamaca kurulmuş bir kasabadır: küçük eski limana doğru inen bembeyaz evler ve onların üstünde Kalkan''ı tanımlayan villa bölgesi — denize bakan, sonsuzluk havuzlu yüzlerce özel villa. Büyük kumsal yoktur; denize plaj kulüpleri ve platformlardan girilir, akşamlar ise kasabanın ünlü teras restoranlarına aittir. Paket aileler yerine çiftler, balayıcılar ve villa grupları için bir destinasyondur. Dik sokaklar ve dağınık villa adresleri, kesin adrese giden özel transferi varışın en mantıklı yolu yapar. TORVIAN: araç başına sabit fiyat, isim tabelasıyla karşılama, uçuş takibi, 7/24.',
  description_de = 'Kalkan liegt 210 km vom Flughafen Antalya (AYT) entfernt, etwa 3 Stunden 10 Minuten mit dem Privattransfer, an der lykischen Küste direkt westlich von Kaş. Die Stadt ist in einen steilen Hang über der Kalamar-Bucht gebaut: weiss getünchte Häuser, die zum kleinen alten Hafen hinabfallen, und darüber das Villenviertel, das Kalkan ausmacht — Hunderte private Villen mit Infinity-Pools mit Blick aufs Meer. Einen grossen Sandstrand gibt es nicht; gebadet wird von Beachclubs und Plattformen, und die Abende gehören den Dachterrassen-Restaurants, für die der Ort bekannt ist. Ein Ziel für Paare, Flitterwöchner und Villengruppen statt für Pauschalfamilien. Die steilen Gassen und verstreuten Villenadressen machen einen Privattransfer mit exakter Adresse zur sinnvollen Ankunft. TORVIAN: Festpreis pro Fahrzeug, Namensschild, Flugverfolgung, 24/7.',
  description_pl = 'Kalkan leży 210 km od lotniska Antalya (AYT), około 3 godzin 10 minut prywatnym transferem, na wybrzeżu licyjskim tuż na zachód od Kaş. To miasteczko wbudowane w strome zbocze nad zatoką Kalamar: pobielone domy schodzące ku małemu staremu portowi, a nad nimi dzielnica willi, która definiuje Kalkan — setki prywatnych willi z basenami infinity z widokiem na morze. Nie ma tu dużej piaszczystej plaży; kąpiele odbywają się z klubów plażowych i pomostów, a wieczory należą do tarasowych restauracji, z których miasteczko słynie. To kierunek dla par, nowożeńców i grup willowych, a nie dla rodzin z pakietów. Strome uliczki i rozproszone adresy willi sprawiają, że prywatny transfer pod dokładny adres to najrozsądniejszy sposób przyjazdu. TORVIAN: stała cena za pojazd, powitanie z tabliczką, monitoring lotu, 24/7.',
  description_ru = 'Калкан находится в 210 км от аэропорта Анталии (AYT), около 3 часов 10 минут на частном трансфере, на Ликийском побережье сразу западнее Каша. Городок построен на крутом склоне над бухтой Каламар: белёные дома спускаются к маленькой старой гавани, а над ними — виллярный район, который и есть Калкан: сотни частных вилл с бассейнами инфинити и видом на море. Большого песчаного пляжа здесь нет; купаются с пляжных клубов и платформ, а вечера принадлежат террасным ресторанам, которыми славится город. Это направление для пар, молодожёнов и компаний, снимающих виллы, а не для семей с пакетными турами. Крутые улочки и разбросанные адреса вилл делают частный трансфер с точным адресом самым разумным способом приезда. TORVIAN: фиксированная цена за автомобиль, встреча с табличкой, отслеживание рейса, круглосуточно.',
  description_nl = 'Kalkan ligt 210 km van de luchthaven Antalya (AYT), ongeveer 3 uur 10 minuten met een privétransfer, aan de Lycische kust net ten westen van Kaş. Het is een stadje dat tegen een steile helling boven de baai van Kalamar is gebouwd: witgekalkte huizen die aflopen naar de kleine oude haven, en daarboven de villawijk die Kalkan bepaalt — honderden privévilla''s met infinity-zwembaden en uitzicht op zee. Een groot zandstrand is er niet; men zwemt vanaf beachclubs en platforms, en de avonden zijn voor de dakterrasrestaurants waar het stadje om bekendstaat. Het is een bestemming voor stellen, honeymooners en villagroepen in plaats van pakketgezinnen. De steile straatjes en verspreide villa-adressen maken een privétransfer met het exacte adres de verstandige manier om aan te komen. TORVIAN: vaste prijs per voertuig, ontvangst met naambord, vluchtmonitoring, 24/7.'
WHERE slug = 'kalkan';


-- ===== FETHIYE — 220 km, 3 h 20 min =====
UPDATE regions SET
  description_en = 'Fethiye is 220 km from Antalya Airport (AYT), about 3 hours 20 minutes by private transfer, a large and lively harbour town at the western end of the Lycian coast. It is the gateway to Ölüdeniz and the Blue Lagoon, to the paragliding launches off Babadağ, to the Lycian rock tombs cut into the cliff above town and to the beach at Çalış. Unlike the boutique quiet of Kaş or Kalkan, Fethiye is a real working town with a big marina, a fish market and a year-round centre. Fethiye is closer to Dalaman Airport (DLM), and if your flight lands there the transfer is short — but plenty of visitors arrive at Antalya, and for them a single door-to-door car with a rest stop beats a bus change through Antalya otogar. TORVIAN: fixed price per vehicle, flight tracking, 24/7.',
  description_tr = 'Fethiye, Antalya Havalimanı''na (AYT) 220 km uzaklıkta, özel transferle yaklaşık 3 saat 20 dakika mesafede, Likya kıyısının batı ucunda büyük ve hareketli bir liman kasabasıdır. Ölüdeniz ve Belceğiz''in, Babadağ''dan yamaç paraşütü kalkışlarının, kasabanın üstündeki kayalara oyulmuş Likya kaya mezarlarının ve Çalış plajının kapısıdır. Kaş ya da Kalkan''ın butik sessizliğinin aksine Fethiye, büyük bir marinası, balık hali ve yıl boyu açık merkeziyle gerçek bir çalışan kasabadır. Fethiye, Dalaman Havalimanı''na (DLM) daha yakındır; uçuşunuz oraya inerse transfer kısadır — ama birçok ziyaretçi Antalya''ya iner ve onlar için molalı, kapıdan kapıya tek araç, Antalya otogarında otobüs aktarmasına yeğdir. TORVIAN: araç başına sabit fiyat, uçuş takibi, 7/24.',
  description_de = 'Fethiye liegt 220 km vom Flughafen Antalya (AYT) entfernt, etwa 3 Stunden 20 Minuten mit dem Privattransfer, eine grosse und lebhafte Hafenstadt am Westende der lykischen Küste. Sie ist das Tor zu Ölüdeniz und der Blauen Lagune, zu den Gleitschirmstarts am Babadağ, zu den in den Fels über der Stadt gehauenen lykischen Felsengräbern und zum Strand von Çalış. Anders als die Boutique-Ruhe von Kaş oder Kalkan ist Fethiye eine echte, lebendige Stadt mit grossem Yachthafen, Fischmarkt und ganzjährigem Zentrum. Fethiye liegt näher am Flughafen Dalaman (DLM); landet Ihr Flug dort, ist der Transfer kurz — doch viele Gäste kommen in Antalya an, und für sie ist ein einziges Tür-zu-Tür-Auto mit Pause besser als ein Umsteigen am Busbahnhof Antalya. TORVIAN: Festpreis pro Fahrzeug, Flugverfolgung, 24/7.',
  description_pl = 'Fethiye leży 220 km od lotniska Antalya (AYT), około 3 godzin 20 minut prywatnym transferem, to duże i tętniące życiem miasto portowe na zachodnim krańcu wybrzeża licyjskiego. Jest bramą do Ölüdeniz i Błękitnej Laguny, do startów paralotni z Babadağ, do licyjskich grobowców skalnych wykutych w klifie nad miastem i do plaży w Çalış. W przeciwieństwie do butikowej ciszy Kaş czy Kalkanu Fethiye to prawdziwe, pracujące miasto z dużą mariną, targiem rybnym i całorocznym centrum. Fethiye leży bliżej lotniska Dalaman (DLM); jeśli lądujesz tam, transfer jest krótki — ale wielu gości przylatuje do Antalyi, a dla nich jeden samochód od drzwi do drzwi z postojem bije przesiadkę autobusową na dworcu w Antalyi. TORVIAN: stała cena za pojazd, monitoring lotu, 24/7.',
  description_ru = 'Фетхие находится в 220 км от аэропорта Анталии (AYT), около 3 часов 20 минут на частном трансфере, — крупный и оживлённый портовый город на западном краю Ликийского побережья. Это ворота к Олюденизу и Голубой лагуне, к площадкам старта парапланов с горы Бабадаг, к ликийским скальным гробницам, вырубленным в утёсе над городом, и к пляжу Чалыш. В отличие от бутиковой тишины Каша или Калкана Фетхие — настоящий живой город с большой мариной, рыбным рынком и круглогодичным центром. Фетхие ближе к аэропорту Даламан (DLM); если ваш рейс садится там, трансфер короткий — но многие прилетают в Анталию, и для них один автомобиль «от двери до двери» с остановкой лучше пересадки на автовокзале Анталии. TORVIAN: фиксированная цена за автомобиль, отслеживание рейса, круглосуточно.',
  description_nl = 'Fethiye ligt 220 km van de luchthaven Antalya (AYT), ongeveer 3 uur 20 minuten met een privétransfer, een grote en levendige havenstad aan het westelijke einde van de Lycische kust. Het is de toegangspoort tot Ölüdeniz en de Blue Lagoon, tot de paraglide-starts vanaf de Babadağ, tot de Lycische rotsgraven die in de klif boven de stad zijn uitgehouwen en tot het strand van Çalış. Anders dan de boetiekrust van Kaş of Kalkan is Fethiye een echte, werkende stad met een grote jachthaven, een vismarkt en een jaarrond centrum. Fethiye ligt dichter bij de luchthaven Dalaman (DLM); landt uw vlucht daar, dan is de transfer kort — maar veel bezoekers komen aan in Antalya, en voor hen is één auto van deur tot deur met een pauze beter dan een busoverstap op het busstation van Antalya. TORVIAN: vaste prijs per voertuig, vluchtmonitoring, 24/7.'
WHERE slug = 'fethiye';


-- ===== MARMARIS — 300 km, 4 h 30 min =====
UPDATE regions SET
  description_en = 'Marmaris lies 300 km from Antalya Airport (AYT), about 4 hours 30 minutes by private transfer — the longest route we run, over in Muğla province at the far end of the coast. It is a big, energetic resort built around a huge marina and a pine-clad bay, known for its seafront Bar Street nightlife, the quieter neighbouring bay of İçmeler and the Blue Voyage gulet cruises that set off from the harbour. Marmaris is much closer to Dalaman Airport (DLM), and if your flight allows it, that is the shorter arrival — but some itineraries and connections land at Antalya, and for a four-and-a-half-hour drive the comfort of one private vehicle, a fixed price agreed in advance and a rest stop matters far more than on a short hop. TORVIAN: fixed price per vehicle, flight tracking, 24/7 with no night surcharge.',
  description_tr = 'Marmaris, Antalya Havalimanı''na (AYT) 300 km uzaklıkta, özel transferle yaklaşık 4 saat 30 dakika mesafededir — işlettiğimiz en uzun rota; kıyının en batı ucunda, Muğla ilinde. Devasa bir marina ve çam kaplı bir koy etrafında kurulmuş büyük, enerjik bir tatil beldesidir; sahildeki Bar Sokağı gece hayatı, daha sakin komşu koy İçmeler ve limandan kalkan Mavi Yolculuk gulet turlarıyla tanınır. Marmaris, Dalaman Havalimanı''na (DLM) çok daha yakındır ve uçuşunuz elveriyorsa varış daha kısadır — ama bazı güzergâh ve bağlantılar Antalya''ya iner; dört buçuk saatlik bir yolculukta tek özel araç konforu, önceden anlaşılan sabit fiyat ve bir mola, kısa mesafeye göre çok daha fazla önem taşır. TORVIAN: araç başına sabit fiyat, uçuş takibi, 7/24 ve gece zammı yok.',
  description_de = 'Marmaris liegt 300 km vom Flughafen Antalya (AYT) entfernt, etwa 4 Stunden 30 Minuten mit dem Privattransfer — die längste Strecke, die wir fahren, drüben in der Provinz Muğla am äussersten Ende der Küste. Es ist ein grosses, energiegeladenes Ferienzentrum rund um einen riesigen Yachthafen und eine kiefernbewachsene Bucht, bekannt für das Nachtleben der Bar Street an der Uferpromenade, die ruhigere Nachbarbucht İçmeler und die Blaue-Reise-Gulet-Törns, die vom Hafen ablegen. Marmaris liegt viel näher am Flughafen Dalaman (DLM), und wenn Ihr Flug es zulässt, ist das die kürzere Ankunft — doch manche Reisepläne landen in Antalya, und bei viereinhalb Stunden zählen der Komfort eines einzigen Privatwagens, ein vorab vereinbarter Festpreis und eine Pause weit mehr als auf kurzer Strecke. TORVIAN: Festpreis pro Fahrzeug, Flugverfolgung, 24/7 ohne Nachtzuschlag.',
  description_pl = 'Marmaris leży 300 km od lotniska Antalya (AYT), około 4 godzin 30 minut prywatnym transferem — to najdłuższa trasa, jaką obsługujemy, w prowincji Muğla na krańcu wybrzeża. To duży, energiczny kurort zbudowany wokół ogromnej mariny i porośniętej sosnami zatoki, znany z nocnego życia nadmorskiej Bar Street, spokojniejszej sąsiedniej zatoki İçmeler i rejsów guletami Blue Voyage wypływających z portu. Marmaris leży znacznie bliżej lotniska Dalaman (DLM) i jeśli lot na to pozwala, to krótszy przylot — ale niektóre plany podróży lądują w Antalyi, a przy czteroipółgodzinnej jeździe komfort jednego prywatnego pojazdu, ustalona z góry stała cena i postój liczą się o wiele bardziej niż na krótkim odcinku. TORVIAN: stała cena za pojazd, monitoring lotu, 24/7 bez dopłaty nocnej.',
  description_ru = 'Мармарис находится в 300 км от аэропорта Анталии (AYT), около 4 часов 30 минут на частном трансфере — это самый длинный маршрут, который мы обслуживаем, в провинции Мугла на дальнем краю побережья. Это большой, энергичный курорт вокруг огромной марины и поросшей соснами бухты, известный ночной жизнью набережной Бар-стрит, более спокойной соседней бухтой Ичмелер и круизами на гулетах Blue Voyage, отходящими от гавани. Мармарис намного ближе к аэропорту Даламан (DLM), и если рейс позволяет, это более короткий прилёт — но некоторые маршруты садятся в Анталии, и на дороге в четыре с половиной часа комфорт одного частного автомобиля, оговорённая заранее фиксированная цена и остановка значат куда больше, чем на коротком отрезке. TORVIAN: фиксированная цена за автомобиль, отслеживание рейса, круглосуточно и без ночной наценки.',
  description_nl = 'Marmaris ligt 300 km van de luchthaven Antalya (AYT), ongeveer 4 uur 30 minuten met een privétransfer — de langste route die wij rijden, in de provincie Muğla aan het uiterste einde van de kust. Het is een grote, energieke badplaats rond een enorme jachthaven en een met dennen begroeide baai, bekend om het nachtleven van de Bar Street aan de boulevard, de rustigere buurbaai İçmeler en de Blue Voyage-guletcruises die vanuit de haven vertrekken. Marmaris ligt veel dichter bij de luchthaven Dalaman (DLM), en als uw vlucht het toelaat is dat de kortere aankomst — maar sommige reisschema''s landen in Antalya, en bij een rit van vierenhalf uur telt het comfort van één privéauto, een vooraf afgesproken vaste prijs en een pauze veel zwaarder dan op een korte hop. TORVIAN: vaste prijs per voertuig, vluchtmonitoring, 24/7 zonder nachttoeslag.'
WHERE slug = 'marmaris';


-- Coverage check:
-- SELECT slug,
--        (description_en IS NOT NULL) AS en, (description_tr IS NOT NULL) AS tr,
--        (description_de IS NOT NULL) AS de, (description_pl IS NOT NULL) AS pl,
--        (description_ru IS NOT NULL) AS ru, (description_nl IS NOT NULL) AS nl
--   FROM regions WHERE slug IN ('kas','kalkan','fethiye','marmaris');
